// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3anyaNdC0QobA2GhuP-3xfudtGSub184',
    appId: '1:29059770366:web:92ba1ed7cb49f1b3e282af',
    messagingSenderId: '29059770366',
    projectId: 'aloo-sbji-mandi',
    authDomain: 'aloo-sbji-mandi.firebaseapp.com',
    storageBucket: 'aloo-sbji-mandi.firebasestorage.app',
    measurementId: 'G-PRML9Z4B5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLrO3RrKgWUHhHPmNt87ejAqYK5AOOH4A',
    appId: '1:29059770366:android:a339130bfaa3acb5e282af',
    messagingSenderId: '29059770366',
    projectId: 'aloo-sbji-mandi',
    storageBucket: 'aloo-sbji-mandi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM_qM-ZkOmhVotocVDOR5V4Kcqvgrzvzo',
    appId: '1:29059770366:ios:2fc4ac5e2495d129e282af',
    messagingSenderId: '29059770366',
    projectId: 'aloo-sbji-mandi',
    storageBucket: 'aloo-sbji-mandi.firebasestorage.app',
    iosBundleId: 'com.example.alooSbjiMandi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM_qM-ZkOmhVotocVDOR5V4Kcqvgrzvzo',
    appId: '1:29059770366:ios:2fc4ac5e2495d129e282af',
    messagingSenderId: '29059770366',
    projectId: 'aloo-sbji-mandi',
    storageBucket: 'aloo-sbji-mandi.firebasestorage.app',
    iosBundleId: 'com.example.alooSbjiMandi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3anyaNdC0QobA2GhuP-3xfudtGSub184',
    appId: '1:29059770366:web:2ab0edda3e2b7793e282af',
    messagingSenderId: '29059770366',
    projectId: 'aloo-sbji-mandi',
    authDomain: 'aloo-sbji-mandi.firebaseapp.com',
    storageBucket: 'aloo-sbji-mandi.firebasestorage.app',
    measurementId: 'G-LCB4CWNX9R',
  );
}
