/// Indian States and their Cities/Districts data
/// Comprehensive list of all Indian states and major cities/districts
library;

class IndianStatesAndCities {
  /// Map of state names to their list of cities/districts
  static const Map<String, List<String>> statesAndCities = {
    'Andhra Pradesh': [
      'Amaravati',
      'Visakhapatnam',
      'Vijayawada',
      'Guntur',
      'Nellore',
      'Kurnool',
      'Rajahmundry',
      'Kakinada',
      'Tirupati',
      'Kadapa',
      'Anantapur',
      'Vizianagaram',
      'Eluru',
      'Ongole',
      'Nandyal',
      'Machilipatnam',
      'Adoni',
      'Tenali',
      'Chittoor',
      'Hindupur',
      'Proddatur',
      'Bhimavaram',
      'Madanapalle',
      'Guntakal',
      'Srikakulam',
    ],
    'Arunachal Pradesh': [
      'Itanagar',
      'Naharlagun',
      'Pasighat',
      'Tawang',
      'Ziro',
      'Bomdila',
      'Along',
      'Tezu',
      'Anini',
      'Daporijo',
      'Namsai',
      'Changlang',
      'Khonsa',
      'Yingkiong',
      'Roing',
    ],
    'Assam': [
      'Guwahati',
      'Silchar',
      'Dibrugarh',
      'Jorhat',
      'Nagaon',
      'Tinsukia',
      'Tezpur',
      'Bongaigaon',
      'Diphu',
      'North Lakhimpur',
      'Dhubri',
      'Karimganj',
      'Sivasagar',
      'Goalpara',
      'Barpeta',
      'Mangaldoi',
      'Nalbari',
      'Rangia',
      'Lumding',
      'Haflong',
    ],
    'Bihar': [
      'Patna',
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Purnia',
      'Darbhanga',
      'Bihar Sharif',
      'Arrah',
      'Begusarai',
      'Katihar',
      'Munger',
      'Chhapra',
      'Samastipur',
      'Hajipur',
      'Sasaram',
      'Dehri',
      'Siwan',
      'Motihari',
      'Nawada',
      'Bagaha',
      'Buxar',
      'Kishanganj',
      'Sitamarhi',
      'Jamalpur',
      'Jehanabad',
    ],
    'Chhattisgarh': [
      'Raipur',
      'Bhilai',
      'Bilaspur',
      'Korba',
      'Durg',
      'Rajnandgaon',
      'Raigarh',
      'Jagdalpur',
      'Ambikapur',
      'Dhamtari',
      'Mahasamund',
      'Chirmiri',
      'Kawardha',
      'Kondagaon',
      'Mungeli',
      'Naila Janjgir',
      'Bemetara',
      'Kanker',
      'Balod',
      'Jashpur',
    ],
    'Goa': [
      'Panaji',
      'Margao',
      'Vasco da Gama',
      'Mapusa',
      'Ponda',
      'Bicholim',
      'Curchorem',
      'Sanquelim',
      'Cuncolim',
      'Quepem',
      'Sanguem',
      'Canacona',
      'Pernem',
      'Valpoi',
      'Mormugao',
    ],
    'Gujarat': [
      'Ahmedabad',
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Junagadh',
      'Gandhinagar',
      'Anand',
      'Nadiad',
      'Morbi',
      'Mehsana',
      'Bharuch',
      'Vapi',
      'Navsari',
      'Veraval',
      'Porbandar',
      'Godhra',
      'Palanpur',
      'Valsad',
      'Botad',
      'Amreli',
      'Deesa',
      'Jetpur',
      'Gondal',
    ],
    'Haryana': [
      'Faridabad',
      'Gurgaon',
      'Panipat',
      'Ambala',
      'Yamunanagar',
      'Rohtak',
      'Hisar',
      'Karnal',
      'Sonipat',
      'Panchkula',
      'Bhiwani',
      'Sirsa',
      'Bahadurgarh',
      'Jind',
      'Thanesar',
      'Kaithal',
      'Rewari',
      'Palwal',
      'Hansi',
      'Mahendragarh',
      'Fatehabad',
      'Ratia',
      'Tohana',
      'Narnaul',
      'Charkhi Dadri',
    ],
    'Himachal Pradesh': [
      'Shimla',
      'Dharamshala',
      'Solan',
      'Mandi',
      'Palampur',
      'Baddi',
      'Nahan',
      'Kullu',
      'Manali',
      'Hamirpur',
      'Una',
      'Chamba',
      'Bilaspur (HP)',
      'Kangra',
      'Dalhousie',
      'Paonta Sahib',
      'Sundernagar',
      'Parwanoo',
      'Santokhgarh',
      'Theog',
    ],
    'Jharkhand': [
      'Ranchi',
      'Jamshedpur',
      'Dhanbad',
      'Bokaro',
      'Deoghar',
      'Hazaribagh',
      'Giridih',
      'Ramgarh',
      'Phusro',
      'Medininagar',
      'Chaibasa',
      'Chatra',
      'Gumla',
      'Lohardaga',
      'Dumka',
      'Jamtara',
      'Pakur',
      'Sahebganj',
      'Godda',
      'Koderma',
    ],
    'Karnataka': [
      'Bengaluru',
      'Mysore',
      'Hubli',
      'Mangalore',
      'Belgaum',
      'Gulbarga',
      'Davanagere',
      'Bellary',
      'Bijapur',
      'Shimoga',
      'Tumkur',
      'Raichur',
      'Bidar',
      'Hospet',
      'Hassan',
      'Gadag',
      'Udupi',
      'Robertson Pet',
      'Bhadravati',
      'Chitradurga',
      'Kolar',
      'Mandya',
      'Chikmagalur',
      'Bagalkot',
      'Ranebennur',
    ],
    'Kerala': [
      'Thiruvananthapuram',
      'Kochi',
      'Kozhikode',
      'Thrissur',
      'Kollam',
      'Palakkad',
      'Alappuzha',
      'Kannur',
      'Kottayam',
      'Malappuram',
      'Kasaragod',
      'Pathanamthitta',
      'Idukki',
      'Wayanad',
      'Ernakulam',
      'Thalassery',
      'Kayamkulam',
      'Vatakara',
      'Manjeri',
      'Ottapalam',
    ],
    'Madhya Pradesh': [
      'Bhopal',
      'Indore',
      'Jabalpur',
      'Gwalior',
      'Ujjain',
      'Sagar',
      'Dewas',
      'Satna',
      'Ratlam',
      'Rewa',
      'Murwara',
      'Singrauli',
      'Burhanpur',
      'Khandwa',
      'Morena',
      'Bhind',
      'Chhindwara',
      'Guna',
      'Shivpuri',
      'Vidisha',
      'Damoh',
      'Chhatarpur',
      'Mandsaur',
      'Neemuch',
      'Hoshangabad',
    ],
    'Maharashtra': [
      'Mumbai',
      'Pune',
      'Nagpur',
      'Thane',
      'Nashik',
      'Aurangabad',
      'Solapur',
      'Kolhapur',
      'Amravati',
      'Navi Mumbai',
      'Sangli',
      'Jalgaon',
      'Akola',
      'Latur',
      'Ahmednagar',
      'Dhule',
      'Chandrapur',
      'Parbhani',
      'Jalna',
      'Bhiwandi',
      'Nanded',
      'Satara',
      'Ratnagiri',
      'Osmanabad',
      'Wardha',
    ],
    'Manipur': [
      'Imphal',
      'Thoubal',
      'Bishnupur',
      'Churachandpur',
      'Kakching',
      'Ukhrul',
      'Senapati',
      'Tamenglong',
      'Chandel',
      'Jiribam',
      'Moirang',
      'Mayang Imphal',
      'Nambol',
      'Wangoi',
      'Yairipok',
    ],
    'Meghalaya': [
      'Shillong',
      'Tura',
      'Nongstoin',
      'Jowai',
      'Baghmara',
      'Williamnagar',
      'Resubelpara',
      'Ampati',
      'Mairang',
      'Khliehriat',
      'Cherrapunji',
      'Dawki',
      'Nongpoh',
      'Mawlai',
      'Madanriting',
    ],
    'Mizoram': [
      'Aizawl',
      'Lunglei',
      'Champhai',
      'Serchhip',
      'Kolasib',
      'Saiha',
      'Lawngtlai',
      'Mamit',
      'Khawzawl',
      'Hnahthial',
      'Saitual',
      'Bairabi',
      'Tlabung',
      'North Vanlaiphai',
      'Thenzawl',
    ],
    'Nagaland': [
      'Kohima',
      'Dimapur',
      'Mokokchung',
      'Tuensang',
      'Wokha',
      'Zunheboto',
      'Phek',
      'Mon',
      'Kiphire',
      'Longleng',
      'Peren',
      'Noklak',
      'Tseminyu',
      'Chumukedima',
      'Shamator',
    ],
    'Odisha': [
      'Bhubaneswar',
      'Cuttack',
      'Rourkela',
      'Berhampur',
      'Sambalpur',
      'Puri',
      'Balasore',
      'Bhadrak',
      'Baripada',
      'Jharsuguda',
      'Jeypore',
      'Angul',
      'Barbil',
      'Paradip',
      'Kendrapara',
      'Sunabeda',
      'Bargarh',
      'Rayagada',
      'Koraput',
      'Phulbani',
    ],
    'Punjab': [
      'Ludhiana',
      'Amritsar',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'Mohali',
      'Pathankot',
      'Hoshiarpur',
      'Batala',
      'Moga',
      'Abohar',
      'Malerkotla',
      'Khanna',
      'Phagwara',
      'Muktsar',
      'Barnala',
      'Rajpura',
      'Firozpur',
      'Kapurthala',
      'Faridkot',
      'Sangrur',
      'Sunam',
      'Gurdaspur',
      'Nabha',
      'Tarn Taran',
    ],
    'Rajasthan': [
      'Jaipur',
      'Jodhpur',
      'Kota',
      'Bikaner',
      'Ajmer',
      'Udaipur',
      'Bhilwara',
      'Alwar',
      'Bharatpur',
      'Sikar',
      'Pali',
      'Sri Ganganagar',
      'Jhunjhunu',
      'Chittorgarh',
      'Tonk',
      'Beawar',
      'Hanumangarh',
      'Gangapur City',
      'Dhaulpur',
      'Sawai Madhopur',
      'Barmer',
      'Nagaur',
      'Churu',
      'Jhalawar',
      'Bundi',
    ],
    'Sikkim': [
      'Gangtok',
      'Namchi',
      'Gyalshing',
      'Mangan',
      'Rangpo',
      'Singtam',
      'Jorethang',
      'Nayabazar',
      'Yuksom',
      'Ravangla',
      'Lachen',
      'Lachung',
      'Pelling',
      'Legship',
      'Chungthang',
    ],
    'Tamil Nadu': [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Salem',
      'Tirunelveli',
      'Tiruppur',
      'Vellore',
      'Erode',
      'Thoothukkudi',
      'Dindigul',
      'Thanjavur',
      'Ranipet',
      'Sivakasi',
      'Karur',
      'Nagercoil',
      'Hosur',
      'Kanchipuram',
      'Kumarapalayam',
      'Kanyakumari',
      'Namakkal',
      'Tiruvannamalai',
      'Pollachi',
      'Kumbakonam',
      'Rajapalayam',
    ],
    'Telangana': [
      'Hyderabad',
      'Warangal',
      'Nizamabad',
      'Karimnagar',
      'Khammam',
      'Ramagundam',
      'Mahbubnagar',
      'Nalgonda',
      'Adilabad',
      'Suryapet',
      'Siddipet',
      'Miryalaguda',
      'Jagtial',
      'Mancherial',
      'Kothagudem',
      'Zahirabad',
      'Bodhan',
      'Sangareddy',
      'Kamareddy',
      'Nirmal',
    ],
    'Tripura': [
      'Agartala',
      'Udaipur (Tripura)',
      'Dharmanagar',
      'Kailasahar',
      'Belonia',
      'Khowai',
      'Ambassa',
      'Sabroom',
      'Sonamura',
      'Kumarghat',
      'Bishalgarh',
      'Amarpur',
      'Melaghar',
      'Jirania',
      'Teliamura',
    ],
    'Uttar Pradesh': [
      'Lucknow',
      'Kanpur',
      'Agra',
      'Varanasi',
      'Prayagraj',
      'Meerut',
      'Ghaziabad',
      'Noida',
      'Bareilly',
      'Aligarh',
      'Moradabad',
      'Saharanpur',
      'Gorakhpur',
      'Faizabad',
      'Firozabad',
      'Jhansi',
      'Muzaffarnagar',
      'Mathura',
      'Rampur',
      'Shahjahanpur',
      'Farrukhabad',
      'Mau',
      'Hapur',
      'Etawah',
      'Mirzapur',
      'Bulandshahr',
      'Sambhal',
      'Amroha',
      'Hardoi',
      'Fatehpur',
      'Raebareli',
      'Orai',
      'Sitapur',
      'Bahraich',
      'Modinagar',
      'Unnao',
      'Jaunpur',
      'Lakhimpur',
      'Hathras',
      'Banda',
      'Lalitpur',
      'Deoria',
      'Sultanpur',
      'Azamgarh',
      'Bijnor',
    ],
    'Uttarakhand': [
      'Dehradun',
      'Haridwar',
      'Rishikesh',
      'Roorkee',
      'Haldwani',
      'Kashipur',
      'Rudrapur',
      'Nainital',
      'Almora',
      'Pithoragarh',
      'Mussoorie',
      'Pauri',
      'Chamoli',
      'Uttarkashi',
      'Tehri',
      'Bageshwar',
      'Champawat',
      'Kotdwar',
      'Ramnagar',
      'Jaspur',
    ],
    'West Bengal': [
      'Kolkata',
      'Howrah',
      'Durgapur',
      'Asansol',
      'Siliguri',
      'Bardhaman',
      'Malda',
      'Baharampur',
      'Habra',
      'Kharagpur',
      'Shantipur',
      'Dankuni',
      'Dhulian',
      'Ranaghat',
      'Haldia',
      'Raiganj',
      'Krishnanagar',
      'Nabadwip',
      'Medinipur',
      'Jalpaiguri',
      'Balurghat',
      'Basirhat',
      'Bankura',
      'Cooch Behar',
      'Darjeeling',
    ],
    // Union Territories
    'Andaman and Nicobar Islands': [
      'Port Blair',
      'Diglipur',
      'Rangat',
      'Mayabunder',
      'Car Nicobar',
      'Bamboo Flat',
      'Garacharma',
      'Prothrapur',
      'Pahargaon',
      'Ferrargunj',
    ],
    'Chandigarh': [
      'Chandigarh',
      'Manimajra',
      'Burail',
      'Maloya',
      'Dhanas',
      'Kaimbwala',
      'Hallomajra',
      'Khuda Lahora',
      'Sector 17',
      'Sector 22',
    ],
    'Dadra and Nagar Haveli and Daman and Diu': [
      'Daman',
      'Diu',
      'Silvassa',
      'Amli',
      'Khanvel',
      'Vapi',
      'Dabhel',
      'Samarvarni',
      'Kadaiya',
      'Dunetha',
    ],
    'Delhi': [
      'New Delhi',
      'North Delhi',
      'South Delhi',
      'East Delhi',
      'West Delhi',
      'Central Delhi',
      'North East Delhi',
      'North West Delhi',
      'South West Delhi',
      'South East Delhi',
      'Shahdara',
      'Dwarka',
      'Rohini',
      'Pitampura',
      'Narela',
      'Najafgarh',
      'Mehrauli',
      'Okhla',
      'Chandni Chowk',
      'Karol Bagh',
    ],
    'Jammu and Kashmir': [
      'Srinagar',
      'Jammu',
      'Anantnag',
      'Baramulla',
      'Sopore',
      'Udhampur',
      'Kathua',
      'Kupwara',
      'Pulwama',
      'Rajouri',
      'Poonch',
      'Kishtwar',
      'Kulgam',
      'Bandipore',
      'Ganderbal',
      'Reasi',
      'Samba',
      'Shopian',
      'Budgam',
      'Doda',
    ],
    'Ladakh': [
      'Leh',
      'Kargil',
      'Diskit',
      'Nyoma',
      'Hanle',
      'Tangtse',
      'Turtuk',
      'Zanskar',
      'Drass',
      'Sankoo',
    ],
    'Lakshadweep': [
      'Kavaratti',
      'Agatti',
      'Amini',
      'Andrott',
      'Kadmat',
      'Kalpeni',
      'Kiltan',
      'Chetlat',
      'Bitra',
      'Minicoy',
    ],
    'Puducherry': [
      'Puducherry',
      'Karaikal',
      'Mahe',
      'Yanam',
      'Ozhukarai',
      'Villianur',
      'Bahour',
      'Ariyankuppam',
      'Nettapakkam',
      'Mannadipet',
    ],
  };

  /// Get all state names
  static List<String> get allStates => statesAndCities.keys.toList()..sort();

  /// Get cities for a given state
  static List<String> getCitiesForState(String state) {
    return statesAndCities[state] ?? [];
  }
}
