class AdminKeywords {
  /// Keys already present in tr() in lib/screens/admin
  static const List<String> localizedKeys = [
    'admin_dashboard',
    'welcome_master',
    'welcome_admin',
    'full_control_platform_admins',
    'manage_your_platform',
    'advertisement_overview',
    'pending_ads',
    'active_ads',
    'total_ads',
    'revenue',
    'quick_actions',
    'manage_advertisements_title',
    'pending_requests',
    'send_notification',
    'broadcast_message_users',
    'manage_admins_title',
    'create_edit_remove_admins',
    'advertisement_approved',
    'failed_to_approve',
    'reject_advertisement',
    'rejection_reason',
    'enter_reason_for_rejection',
    'cancel',
    'advertisement_rejected',
    'failed_to_reject',
    'reject',
    'confirm_payment',
    'confirm_payment_message',
    'payment_confirmed_active',
    'failed_to_confirm',
    'confirm',
    'delete_advertisement',
    'advertisement_deleted',
    'failed_to_delete',
    'delete',
    'edit_ad_image',
    'edit_advertisement',
    'title_required',
    'new_image_tap_change',
    'tap_to_replace',
    'tap_add_image',
    'description',
    'price_rupees',
    'duration_label',
    'days',
    'status_label',
    'all',
    'pending_tab',
    'approved_tab',
    'add_banner',
    'edit_banner_image',
    'add_new_banner',
    'banner_title_required',
    'banner_title_hint',
    'please_enter_a_title',
    'please_enter_a_message',
    'title_less_than_200',
    'message_less_than_1000',
    'confirm_broadcast',
    'send_notification_to_all_msg',
    'with_image_yes',
    'notification_sent_successfully',
    'authentication_required',
    'session_expired_login_again',
    'ok',
    'failed_to_send_notification',
    'send_broadcast_notification_title',
    'sending_notification_to_all',
    'broadcast_notification_info',
    'notification_title_required',
    'eg_important_update',
    'notification_message_required',
    'eg_important_announcement',
    'notification_image_optional',
    'change_image',
    'remove',
    'add_image',
    'send_to_all_users',
    'delete_feedback',
    'status_updated_to',
    'feedback_deleted',
    'sample_feedbacks_added',
    'add_samples',
    'failed_to_load_admins',
    'create_new_admin',
    'first_name',
    'last_name',
    'phone_number',
    'email_optional',
    'password',
    'fill_all_required_fields',
    'password_min_6_chars',
    'admin_created_success',
    'failed_to_create_admin',
    'create_admin_button',
    'edit_admin',
    'new_password_optional',
    'admin_updated_success',
    'failed_to_update_admin',
    'update',
    'delete_admin',
    'are_you_sure_delete_admin',
    'this_action_cannot_be_undone',
    'demote_admin',
    'demote_prefix',
    'demote_suffix',
    'role_farmer',
    'role_trader',
    'role_cold_storage',
    'role_aloo_mitra',
    'admin_demoted_success',
    'failed_to_demote_admin',
    'demote',
    'manage_admins',
    'add_admin_action',
    'no_admins_found',
    'tap_plus_create_admin',
    'master_badge',
    'admin_badge',
    'edit',
    'tap_to_change_banner',
    'tap_upload_banner_image',
    'jpg_png_gallery',
    'description_optional',
    'banner_title_required_error',
    'please_upload_banner_image',
    'banner_created_activated',
    'failed_to_create_banner',
    'create_activate',
    'no_advertisements_found',
    'untitled',
    'slide_prefix',
    'approve',
    'confirm_pay_btn',
    'not_available',
  ];

  /// Hardcoded strings in lib/screens/admin that need localization
  static const List<String> hardcodedStrings = [
    'Manage Users',
    'All Users',
    'Farmers',
    'Traders',
    'Cold Storage',
    'Aloo Mitra',
    'Admins',
    'No users found',
    'unknown',
    'Farmer',
    'Trader',
    'User',
    'Unknown User',
    'No message',
    'Update Status:',
    'Farmer 👨‍🌾',
    'Trader 🏪',
    'Cold Storage ❄️',
    'Aloo Mitra 🤝',
    'User Feedbacks',
    'Total',
    'Pending',
    'Reviewed',
    'Resolved',
    'All',
    'No feedbacks yet',
    'User feedbacks will appear here',
    'N/A',
    'min ago',
    'hours ago',
    'days ago',
    'Title: ',
    'Message: ',
    'Error: ',
    '₹',
    'Are you sure you want to permanently delete ',
  ];
}
