import 'indian_states_cities.dart';

/// State, District and Village data for India
/// Merges potato-farming region data with comprehensive IndianStatesAndCities
class StateCityData {
  // Legacy: State -> Cities (Districts)
  static const Map<String, List<String>> stateCities = {
    'Uttar Pradesh': [
      'Agra',
      'Aligarh',
      'Allahabad',
      'Bareilly',
      'Bulandshahr',
      'Etawah',
      'Farrukhabad',
      'Firozabad',
      'Ghaziabad',
      'Hathras',
      'Kanpur',
      'Lucknow',
      'Mainpuri',
      'Mathura',
      'Meerut',
      'Moradabad',
      'Muzaffarnagar',
      'Noida',
      'Saharanpur',
      'Varanasi',
    ],
    'Gujarat': [
      'Ahmedabad',
      'Banaskantha',
      'Gandhinagar',
      'Mehsana',
      'Patan',
      'Rajkot',
      'Sabarkantha',
      'Surat',
      'Vadodara',
    ],
    'Punjab': [
      'Amritsar',
      'Bathinda',
      'Faridkot',
      'Ferozepur',
      'Gurdaspur',
      'Hoshiarpur',
      'Jalandhar',
      'Kapurthala',
      'Ludhiana',
      'Moga',
      'Patiala',
      'Sangrur',
    ],
    'West Bengal': [
      'Bankura',
      'Bardhaman',
      'Birbhum',
      'Cooch Behar',
      'Hooghly',
      'Howrah',
      'Kolkata',
      'Malda',
      'Murshidabad',
      'Nadia',
      'North 24 Parganas',
      'South 24 Parganas',
    ],
    'Bihar': [
      'Begusarai',
      'Bhojpur',
      'Nalanda',
      'Patna',
      'Samastipur',
      'Saran',
      'Vaishali',
    ],
    'Madhya Pradesh': [
      'Bhopal',
      'Gwalior',
      'Indore',
      'Jabalpur',
      'Ratlam',
      'Sagar',
      'Ujjain',
    ],
    'Maharashtra': [
      'Ahmednagar',
      'Aurangabad',
      'Chandrapur',
      'Jalgaon',
      'Kolhapur',
      'Latur',
      'Mumbai',
      'Nagpur',
      'Nashik',
      'Pune',
      'Sangli',
      'Satara',
      'Solapur',
    ],
    'Haryana': [
      'Ambala',
      'Bhiwani',
      'Faridabad',
      'Gurgaon',
      'Hisar',
      'Jhajjar',
      'Karnal',
      'Kurukshetra',
      'Panipat',
      'Rohtak',
      'Sonipat',
      'Yamunanagar',
    ],
    'Karnataka': [
      'Bangalore',
      'Belgaum',
      'Bellary',
      'Bidar',
      'Dharwad',
      'Hassan',
      'Kolar',
      'Mysore',
      'Shimoga',
      'Tumkur',
    ],
    'Rajasthan': [
      'Ajmer',
      'Alwar',
      'Bikaner',
      'Bharatpur',
      'Jaipur',
      'Jodhpur',
      'Kota',
      'Sikar',
      'Udaipur',
    ],
  };

  /// District -> Villages mapping (for cold storages in rural areas)
  static const Map<String, List<String>> districtVillages = {
    // Uttar Pradesh Districts
    'Agra': [
      'Agra City',
      'Fatehabad',
      'Kheragarh',
      'Etmadpur',
      'Bah',
      'Khandauli',
      'Akola',
      'Pinahat',
      'Shamshabad',
      'Jagner',
    ],
    'Aligarh': [
      'Aligarh City',
      'Atrauli',
      'Khair',
      'Iglas',
      'Gabhana',
      'Tappal',
      'Chandaus',
      'Lodha',
      'Jawan',
    ],
    'Allahabad': [
      'Allahabad City',
      'Phulpur',
      'Handia',
      'Karchana',
      'Meja',
      'Bara',
      'Jasra',
      'Chaka',
    ],
    'Bareilly': [
      'Bareilly City',
      'Aonla',
      'Faridpur',
      'Baheri',
      'Meerganj',
      'Nawabganj',
      'Richha',
      'Bhojipura',
    ],
    'Bulandshahr': [
      'Bulandshahr City',
      'Khurja',
      'Sikandrabad',
      'Jahangirabad',
      'Shikarpur',
      'Anupshahr',
      'Gulaothi',
      'Debai',
    ],
    'Etawah': [
      'Etawah City',
      'Bharthana',
      'Jaswantnagar',
      'Saifai',
      'Basrehar',
      'Chakarnagar',
      'Takha',
      'Lakhna',
    ],
    'Farrukhabad': [
      'Farrukhabad City',
      'Fatehgarh',
      'Kaimganj',
      'Amritpur',
      'Rajepur',
      'Mohammadabad',
      'Kamalganj',
    ],
    'Firozabad': [
      'Firozabad City',
      'Tundla',
      'Shikohabad',
      'Jasrana',
      'Sirsaganj',
      'Madanpur',
      'Narkhi',
      'Eka',
    ],
    'Ghaziabad': [
      'Ghaziabad City',
      'Modinagar',
      'Muradnagar',
      'Loni',
      'Hapur',
      'Pilkhuwa',
      'Bhojpur',
      'Dasna',
    ],
    'Hathras': [
      'Hathras City',
      'Sadabad',
      'Sikandra Rao',
      'Sasni',
      'Mursan',
      'Hasayan',
      'Mendu',
    ],
    'Kanpur': [
      'Kanpur City',
      'Bilhaur',
      'Bhitargaon',
      'Ghatampur',
      'Sachendi',
      'Kalyanpur',
      'Shivrajpur',
    ],
    'Lucknow': [
      'Lucknow City',
      'Mohanlalganj',
      'Malihabad',
      'Bakshi Ka Talab',
      'Sarojininagar',
      'Chinhat',
      'Kakori',
    ],
    'Mainpuri': [
      'Mainpuri City',
      'Bhogaon',
      'Karhal',
      'Kishni',
      'Kurawali',
      'Ghiror',
      'Barnahal',
      'Sultanganj',
    ],
    'Mathura': [
      'Mathura City',
      'Vrindavan',
      'Govardhan',
      'Chhata',
      'Mant',
      'Raya',
      'Farah',
      'Baldeo',
      'Sonkh',
    ],
    'Meerut': [
      'Meerut City',
      'Sardhana',
      'Mawana',
      'Daurala',
      'Parikshitgarh',
      'Hastinapur',
      'Machhara',
      'Rajpura',
    ],
    'Moradabad': [
      'Moradabad City',
      'Sambhal',
      'Chandausi',
      'Bilari',
      'Thakurdwara',
      'Kundarki',
      'Amroha',
    ],
    'Muzaffarnagar': [
      'Muzaffarnagar City',
      'Shamli',
      'Kairana',
      'Budhana',
      'Jansath',
      'Khatauli',
      'Charthawal',
      'Purkazi',
    ],
    'Noida': [
      'Noida City',
      'Greater Noida',
      'Dadri',
      'Jewar',
      'Dankaur',
      'Bisrakh',
    ],
    'Saharanpur': [
      'Saharanpur City',
      'Deoband',
      'Behat',
      'Nakur',
      'Rampur Maniharan',
      'Gangoh',
      'Nagal',
      'Sarsawa',
    ],
    'Varanasi': [
      'Varanasi City',
      'Pindra',
      'Kashi Vidyapeeth',
      'Rohania',
      'Cholapur',
      'Harhua',
      'Arazilines',
    ],

    // Gujarat Districts
    'Ahmedabad': [
      'Ahmedabad City',
      'Dholka',
      'Bavla',
      'Sanand',
      'Viramgam',
      'Dhandhuka',
      'Mandal',
      'Detroj-Rampura',
    ],
    'Banaskantha': [
      'Palanpur',
      'Deesa',
      'Dhanera',
      'Tharad',
      'Dantiwada',
      'Amirgadh',
      'Vadgam',
      'Kankrej',
      'Bhabhar',
    ],
    'Gandhinagar': [
      'Gandhinagar City',
      'Kalol',
      'Mansa',
      'Dehgam',
      'Pethapur',
      'Raysan',
    ],
    'Mehsana': [
      'Mehsana City',
      'Visnagar',
      'Unjha',
      'Kadi',
      'Vijapur',
      'Kheralu',
      'Satlasana',
      'Jotana',
      'Becharaji',
    ],
    'Patan': [
      'Patan City',
      'Siddhpur',
      'Chanasma',
      'Radhanpur',
      'Santalpur',
      'Harij',
      'Sami',
    ],
    'Rajkot': [
      'Rajkot City',
      'Gondal',
      'Jetpur',
      'Dhoraji',
      'Morbi',
      'Wankaner',
      'Jasdan',
      'Upleta',
      'Paddhari',
    ],
    'Sabarkantha': [
      'Himmatnagar',
      'Modasa',
      'Idar',
      'Vadali',
      'Talod',
      'Prantij',
      'Dhansura',
      'Meghraj',
      'Khedbrahma',
    ],
    'Surat': [
      'Surat City',
      'Bardoli',
      'Mandvi',
      'Mahuva',
      'Olpad',
      'Palsana',
      'Kamrej',
      'Chorasi',
      'Choryasi',
    ],
    'Vadodara': [
      'Vadodara City',
      'Padra',
      'Savli',
      'Dabhoi',
      'Karjan',
      'Waghodia',
      'Sinor',
      'Sankheda',
    ],

    // Punjab Districts
    'Amritsar': [
      'Amritsar City',
      'Ajnala',
      'Baba Bakala',
      'Majitha',
      'Rayya',
      'Verka',
      'Lopoke',
      'Jandiala Guru',
    ],
    'Bathinda': [
      'Bathinda City',
      'Rampura Phul',
      'Goniana',
      'Sangat',
      'Talwandi Sabo',
      'Maur',
      'Phul',
    ],
    'Faridkot': ['Faridkot City', 'Kotkapura', 'Jaitu', 'Sadiq'],
    'Ferozepur': [
      'Ferozepur City',
      'Zira',
      'Guru Har Sahai',
      'Makhu',
      'Talwandi Bhai',
      'Ghall Khurd',
      'Mamdot',
    ],
    'Gurdaspur': [
      'Gurdaspur City',
      'Batala',
      'Qadian',
      'Dera Baba Nanak',
      'Fatehgarh Churian',
      'Dorangla',
      'Dinanagar',
    ],
    'Hoshiarpur': [
      'Hoshiarpur City',
      'Garhshankar',
      'Dasuya',
      'Mukerian',
      'Tanda',
      'Hajipur',
      'Bhunga',
    ],
    'Jalandhar': [
      'Jalandhar City',
      'Phagwara',
      'Nakodar',
      'Shahkot',
      'Phillaur',
      'Kartarpur',
      'Lohian',
      'Bhogpur',
    ],
    'Kapurthala': [
      'Kapurthala City',
      'Phagwara',
      'Sultanpur Lodhi',
      'Dhilwan',
      'Bhulath',
      'Begowal',
    ],
    'Ludhiana': [
      'Ludhiana City',
      'Khanna',
      'Jagraon',
      'Raikot',
      'Samrala',
      'Machhiwara',
      'Payal',
      'Doraha',
      'Sahnewal',
    ],
    'Moga': [
      'Moga City',
      'Baghapurana',
      'Dharamkot',
      'Nihal Singh Wala',
      'Kot Ise Khan',
      'Ajitwal',
    ],
    'Patiala': [
      'Patiala City',
      'Rajpura',
      'Samana',
      'Nabha',
      'Patran',
      'Bhunerheri',
      'Ghagga',
      'Ghanaur',
    ],
    'Sangrur': [
      'Sangrur City',
      'Malerkotla',
      'Barnala',
      'Dhuri',
      'Sunam',
      'Moonak',
      'Lehra',
      'Andana',
      'Sherpur',
    ],

    // Bihar Districts
    'Begusarai': [
      'Begusarai City',
      'Barauni',
      'Balia',
      'Bachhwara',
      'Bhagwanpur',
      'Birpur',
      'Cheria Bariarpur',
      'Garhpura',
    ],
    'Bhojpur': [
      'Arrah',
      'Jagdishpur',
      'Piro',
      'Koilwar',
      'Bihiya',
      'Sandesh',
      'Sahar',
      'Shahpur',
      'Tarari',
    ],
    'Nalanda': [
      'Bihar Sharif',
      'Rajgir',
      'Hilsa',
      'Ekangarsarai',
      'Noorsarai',
      'Islampur',
      'Silao',
      'Harnaut',
      'Rahui',
    ],
    'Patna': [
      'Patna City',
      'Danapur',
      'Khagaul',
      'Phulwari Sharif',
      'Fatuha',
      'Bakhtiarpur',
      'Maner',
      'Mokama',
      'Bikram',
    ],
    'Samastipur': [
      'Samastipur City',
      'Dalsinghsarai',
      'Rosera',
      'Pusa',
      'Morwa',
      'Kalyanpur',
      'Warisnagar',
      'Mohanpur',
      'Sarairanjan',
    ],
    'Saran': [
      'Chhapra',
      'Dighwara',
      'Marhowrah',
      'Sonpur',
      'Baniapur',
      'Amnour',
      'Parsa',
      'Revelganj',
      'Dariapur',
    ],
    'Vaishali': [
      'Hajipur',
      'Lalganj',
      'Mahua',
      'Patepur',
      'Raghopur',
      'Vaishali',
      'Bidupur',
      'Desari',
      'Bhagwanpur',
    ],

    // Madhya Pradesh Districts
    'Bhopal': [
      'Bhopal City',
      'Berasia',
      'Huzur',
      'Phanda',
      'Govindpura',
      'Misrod',
    ],
    'Gwalior': ['Gwalior City', 'Dabra', 'Morar', 'Ghatigaon', 'Bhitarwar'],
    'Indore': ['Indore City', 'Mhow', 'Sanwer', 'Depalpur', 'Hatod', 'Betma'],
    'Jabalpur': [
      'Jabalpur City',
      'Sihora',
      'Patan',
      'Kundam',
      'Bargi',
      'Panagar',
      'Majholi',
      'Shahpura',
    ],
    'Ratlam': ['Ratlam City', 'Jaora', 'Alot', 'Sailana', 'Bajna', 'Piploda'],
    'Sagar': [
      'Sagar City',
      'Bina',
      'Khurai',
      'Rahatgarh',
      'Deori',
      'Shahgarh',
      'Banda',
      'Malthone',
    ],
    'Ujjain': [
      'Ujjain City',
      'Tarana',
      'Mahidpur',
      'Nagda',
      'Ghatiya',
      'Khachrod',
      'Badnagar',
    ],

    // Haryana Districts
    'Ambala': [
      'Ambala City',
      'Ambala Cantt',
      'Barara',
      'Naraingarh',
      'Shahzadpur',
      'Saha',
    ],
    'Bhiwani': [
      'Bhiwani City',
      'Charkhi Dadri',
      'Loharu',
      'Siwani',
      'Tosham',
      'Behal',
      'Kairu',
    ],
    'Faridabad': ['Faridabad City', 'Ballabgarh', 'Palwal', 'Hodal', 'Hathin'],
    'Gurgaon': [
      'Gurgaon City',
      'Sohna',
      'Pataudi',
      'Manesar',
      'Farukhnagar',
      'Wazirabad',
    ],
    'Hisar': [
      'Hisar City',
      'Hansi',
      'Barwala',
      'Uklana',
      'Adampur',
      'Narnaund',
      'Bass',
      'Agroha',
    ],
    'Jhajjar': [
      'Jhajjar City',
      'Bahadurgarh',
      'Beri',
      'Machhrauli',
      'Salhawas',
      'Dighal',
    ],
    'Karnal': [
      'Karnal City',
      'Gharaunda',
      'Nilokheri',
      'Assandh',
      'Indri',
      'Nissing',
      'Taraori',
    ],
    'Kurukshetra': [
      'Kurukshetra City',
      'Thanesar',
      'Pehowa',
      'Shahabad',
      'Ladwa',
      'Ismailabad',
      'Babain',
    ],
    'Panipat': [
      'Panipat City',
      'Samalkha',
      'Israna',
      'Madlauda',
      'Bapoli',
      'Sanauli Khurd',
    ],
    'Rohtak': [
      'Rohtak City',
      'Kalanaur',
      'Meham',
      'Lakhan Majra',
      'Sampla',
      'Dighal',
      'Asthal Bohar',
    ],
    'Sonipat': [
      'Sonipat City',
      'Ganaur',
      'Gohana',
      'Kharkhoda',
      'Mundlana',
      'Rai',
      'Kathura',
    ],
    'Yamunanagar': [
      'Yamunanagar City',
      'Jagadhri',
      'Chhachhrauli',
      'Radaur',
      'Bilaspur',
      'Sadhaura',
    ],

    // Karnataka Districts
    'Bangalore': [
      'Bangalore City',
      'Yelahanka',
      'Anekal',
      'Devanahalli',
      'Doddaballapur',
      'Hoskote',
      'Nelamangala',
    ],
    'Belgaum': [
      'Belgaum City',
      'Gokak',
      'Chikodi',
      'Athni',
      'Raibag',
      'Saundatti',
      'Bailhongal',
      'Khanapur',
      'Hukkeri',
    ],
    'Bellary': [
      'Bellary City',
      'Hospet',
      'Sandur',
      'Kudligi',
      'Siruguppa',
      'Hadagalli',
      'Hagaribommanahalli',
    ],
    'Bidar': [
      'Bidar City',
      'Basavakalyan',
      'Humnabad',
      'Bhalki',
      'Aurad',
      'Chitguppa',
      'Kamalnagar',
    ],
    'Dharwad': [
      'Dharwad City',
      'Hubli',
      'Alnavar',
      'Kalghatgi',
      'Navalgund',
      'Kundgol',
      'Annigeri',
    ],
    'Hassan': [
      'Hassan City',
      'Arsikere',
      'Channarayapatna',
      'Belur',
      'Sakleshpur',
      'Holenarasipura',
      'Alur',
    ],
    'Kolar': [
      'Kolar City',
      'KGF',
      'Bangarapet',
      'Mulbagal',
      'Malur',
      'Srinivaspur',
    ],
    'Mysore': [
      'Mysore City',
      'Nanjangud',
      'T. Narasipur',
      'Hunsur',
      'Periyapatna',
      'K.R. Nagar',
      'H.D. Kote',
    ],
    'Shimoga': [
      'Shimoga City',
      'Bhadravati',
      'Sagar',
      'Shikaripura',
      'Tirthahalli',
      'Hosanagara',
      'Sorab',
    ],
    'Tumkur': [
      'Tumkur City',
      'Tiptur',
      'Sira',
      'Kunigal',
      'Madhugiri',
      'Pavagada',
      'Gubbi',
      'Koratagere',
    ],

    // Rajasthan Districts
    'Ajmer': [
      'Ajmer City',
      'Kishangarh',
      'Beawar',
      'Nasirabad',
      'Pushkar',
      'Kekri',
      'Sarwar',
      'Pisangan',
    ],
    'Alwar': [
      'Alwar City',
      'Bhiwadi',
      'Tijara',
      'Kishangarh Bas',
      'Rajgarh',
      'Ramgarh',
      'Behror',
      'Neemrana',
      'Bansur',
    ],
    'Bikaner': [
      'Bikaner City',
      'Nokha',
      'Lunkaransar',
      'Dungargarh',
      'Kolayat',
      'Khajuwala',
      'Poogal',
    ],
    'Bharatpur': [
      'Bharatpur City',
      'Deeg',
      'Kumher',
      'Nadbai',
      'Weir',
      'Bayana',
      'Roopbas',
      'Kaman',
    ],
    'Jaipur': [
      'Jaipur City',
      'Sanganer',
      'Chomu',
      'Amber',
      'Shahpura',
      'Bassi',
      'Kotputli',
      'Phagi',
      'Chaksu',
      'Jamwa Ramgarh',
    ],
    'Jodhpur': [
      'Jodhpur City',
      'Phalodi',
      'Osian',
      'Bilara',
      'Shergarh',
      'Bhopalgarh',
      'Pipar',
      'Luni',
    ],
    'Kota': [
      'Kota City',
      'Ramganj Mandi',
      'Sangod',
      'Ladpura',
      'Digod',
      'Itawa',
      'Pipalda',
      'Chechat',
    ],
    'Sikar': [
      'Sikar City',
      'Fatehpur',
      'Lachhmangarh',
      'Neem Ka Thana',
      'Danta Ramgarh',
      'Khandela',
      'Piprali',
      'Dhod',
    ],
    'Udaipur': [
      'Udaipur City',
      'Nathdwara',
      'Rajsamand',
      'Salumber',
      'Vallabhnagar',
      'Mavli',
      'Bhinder',
      'Gogunda',
      'Kherwara',
    ],

    // West Bengal Districts
    'Bankura': [
      'Bankura City',
      'Bishnupur',
      'Sonamukhi',
      'Onda',
      'Barjora',
      'Mejia',
      'Khatra',
      'Indpur',
      'Kotulpur',
    ],
    'Bardhaman': [
      'Bardhaman City',
      'Durgapur',
      'Asansol',
      'Kalna',
      'Katwa',
      'Memari',
      'Bhatar',
      'Monteswar',
      'Raina',
    ],
    'Birbhum': [
      'Suri',
      'Bolpur',
      'Rampurhat',
      'Sainthia',
      'Dubrajpur',
      'Nalhati',
      'Labhpur',
      'Nanoor',
      'Md. Bazar',
    ],
    'Cooch Behar': [
      'Cooch Behar City',
      'Dinhata',
      'Mathabhanga',
      'Tufanganj',
      'Mekhliganj',
      'Sitalkuchi',
      'Haldibari',
    ],
    'Hooghly': [
      'Chinsurah',
      'Chandannagar',
      'Serampore',
      'Tarakeswar',
      'Arambagh',
      'Pandua',
      'Polba',
      'Balagarh',
      'Goghat',
    ],
    'Howrah': [
      'Howrah City',
      'Uluberia',
      'Domjur',
      'Panchla',
      'Amta',
      'Bagnan',
      'Shyampur',
      'Jagatballavpur',
    ],
    'Kolkata': [
      'Kolkata City',
      'Salt Lake',
      'New Town',
      'Behala',
      'Dum Dum',
      'Tollygunge',
      'Jadavpur',
      'Kasba',
    ],
    'Malda': [
      'English Bazar',
      'Old Malda',
      'Kaliachak',
      'Gazole',
      'Ratua',
      'Manikchak',
      'Harishchandrapur',
      'Bamongola',
    ],
    'Murshidabad': [
      'Berhampore',
      'Murshidabad City',
      'Jangipur',
      'Kandi',
      'Lalgola',
      'Domkal',
      'Raghunathganj',
      'Suti',
    ],
    'Nadia': [
      'Krishnanagar',
      'Nabadwip',
      'Ranaghat',
      'Kalyani',
      'Tehatta',
      'Chapra',
      'Haringhata',
      'Santipur',
    ],
    'North 24 Parganas': [
      'Barasat',
      'Barrackpore',
      'Bongaon',
      'Basirhat',
      'Madhyamgram',
      'Habra',
      'Naihati',
      'Baduria',
      'Haroa',
    ],
    'South 24 Parganas': [
      'Alipore',
      'Diamond Harbour',
      'Baruipur',
      'Kakdwip',
      'Magrahat',
      'Canning',
      'Sonarpur',
      'Budge Budge',
      'Patharpratima',
    ],

    // Maharashtra Districts
    'Ahmednagar': [
      'Ahmednagar City',
      'Shrirampur',
      'Rahuri',
      'Sangamner',
      'Kopargaon',
      'Shevgaon',
      'Newasa',
      'Pathardi',
    ],
    'Aurangabad': [
      'Aurangabad City',
      'Vaijapur',
      'Gangapur',
      'Paithan',
      'Kannad',
      'Khuldabad',
      'Sillod',
    ],
    'Chandrapur': [
      'Chandrapur City',
      'Ballarpur',
      'Warora',
      'Mul',
      'Gondpipri',
      'Rajura',
      'Bhadravati',
    ],
    'Jalgaon': [
      'Jalgaon City',
      'Bhusawal',
      'Pachora',
      'Chopda',
      'Amalner',
      'Erandol',
      'Raver',
    ],
    'Kolhapur': [
      'Kolhapur City',
      'Ichalkaranji',
      'Jaysingpur',
      'Gadhinglaj',
      'Kagal',
      'Hatkanangle',
      'Panhala',
    ],
    'Latur': [
      'Latur City',
      'Udgir',
      'Ausa',
      'Nilanga',
      'Ahmedpur',
      'Chakur',
      'Renapur',
    ],
    'Mumbai': [
      'Mumbai City',
      'Andheri',
      'Bandra',
      'Borivali',
      'Dadar',
      'Goregaon',
      'Malad',
    ],
    'Nagpur': [
      'Nagpur City',
      'Kamptee',
      'Hingna',
      'Ramtek',
      'Katol',
      'Umred',
      'Saoner',
    ],
    'Nashik': [
      'Nashik City',
      'Malegaon',
      'Manmad',
      'Igatpuri',
      'Sinnar',
      'Niphad',
      'Dindori',
    ],
    'Pune': [
      'Pune City',
      'Pimpri-Chinchwad',
      'Baramati',
      'Shirur',
      'Junnar',
      'Indapur',
      'Daund',
      'Bhor',
    ],
    'Sangli': [
      'Sangli City',
      'Miraj',
      'Islampur',
      'Tasgaon',
      'Vita',
      'Shirala',
      'Walwa',
    ],
    'Satara': [
      'Satara City',
      'Karad',
      'Wai',
      'Phaltan',
      'Mahabaleshwar',
      'Koregaon',
      'Jawali',
    ],
    'Solapur': [
      'Solapur City',
      'Pandharpur',
      'Barshi',
      'Akkalkot',
      'Mohol',
      'Karmala',
      'Sangola',
    ],

    // ── Additional UP Districts (from IndianStatesAndCities) ──
    'Prayagraj': [
      'Prayagraj City',
      'Phulpur',
      'Handia',
      'Karchana',
      'Meja',
      'Bara',
      'Jasra',
      'Soraon',
    ],
    'Gorakhpur': [
      'Gorakhpur City',
      'Sahjanwa',
      'Khajni',
      'Campierganj',
      'Pipraich',
      'Gola',
      'Bansgaon',
      'Chauri Chaura',
    ],
    'Faizabad': [
      'Faizabad City',
      'Ayodhya',
      'Tanda',
      'Bikapur',
      'Rudauli',
      'Milkipur',
      'Sohawal',
    ],
    'Jhansi': [
      'Jhansi City',
      'Babina',
      'Mauranipur',
      'Moth',
      'Garautha',
      'Bangra',
      'Chirgaon',
    ],
    'Rampur': [
      'Rampur City',
      'Milak',
      'Bilaspur',
      'Swar',
      'Shahabad',
      'Chamraua',
      'Tanda',
    ],
    'Shahjahanpur': [
      'Shahjahanpur City',
      'Tilhar',
      'Powayan',
      'Jalalabad',
      'Khutar',
      'Dadraul',
      'Nigohi',
    ],
    'Mau': [
      'Mau City',
      'Ghosi',
      'Muhammadabad',
      'Kopaganj',
      'Ratanpura',
      'Doharighat',
    ],
    'Hapur': [
      'Hapur City',
      'Pilkhuwa',
      'Garhmukteshwar',
      'Dhaulana',
      'Simbhaoli',
    ],
    'Mirzapur': [
      'Mirzapur City',
      'Chunar',
      'Marihan',
      'Lalganj',
      'Ahraura',
      'Rajgarh',
      'Vindham',
    ],
    'Sambhal': [
      'Sambhal City',
      'Chandausi',
      'Bahjoi',
      'Gunnaur',
      'Baniyakhera',
      'Rajpura',
    ],
    'Amroha': [
      'Amroha City',
      'Hasanpur',
      'Dhanaura',
      'Gajraula',
      'Naugawan Sadat',
      'Joya',
    ],
    'Hardoi': [
      'Hardoi City',
      'Sandila',
      'Bilgram',
      'Shahabad',
      'Bharawan',
      'Pihani',
      'Sandi',
    ],
    'Fatehpur': [
      'Fatehpur City',
      'Bindki',
      'Khaga',
      'Teliyani',
      'Dhata',
      'Husainganj',
    ],
    'Raebareli': [
      'Raebareli City',
      'Lalganj',
      'Salon',
      'Dalmau',
      'Jais',
      'Unchahar',
      'Maharajganj',
    ],
    'Orai': [
      'Orai City',
      'Kalpi',
      'Konch',
      'Jalaun',
      'Kadaura',
      'Nadigaon',
    ],
    'Sitapur': [
      'Sitapur City',
      'Misrikh',
      'Biswan',
      'Laharpur',
      'Sidhauli',
      'Mahmudabad',
    ],
    'Bahraich': [
      'Bahraich City',
      'Nanpara',
      'Kaiserganj',
      'Payagpur',
      'Fakharpur',
      'Mahsi',
    ],
    'Modinagar': [
      'Modinagar',
      'Muradnagar',
      'Niwari',
      'Bhojpur',
      'Rataul',
    ],
    'Unnao': [
      'Unnao City',
      'Shuklaganj',
      'Hasanganj',
      'Purwa',
      'Bangarmau',
      'Safipur',
    ],
    'Jaunpur': [
      'Jaunpur City',
      'Shahganj',
      'Machhalishahar',
      'Mariahu',
      'Kerakat',
      'Badlapur',
    ],
    'Lakhimpur': [
      'Lakhimpur City',
      'Gola Gokarannath',
      'Palia Kalan',
      'Nighasan',
      'Mohammadi',
      'Mithaura',
    ],
    'Banda': [
      'Banda City',
      'Baberu',
      'Naraini',
      'Atarra',
      'Tindwari',
      'Kamasin',
    ],
    'Lalitpur': [
      'Lalitpur City',
      'Mehrauni',
      'Talbehat',
      'Bar',
      'Pali',
      'Madawara',
    ],
    'Deoria': [
      'Deoria City',
      'Bhatpar Rani',
      'Salempur',
      'Pathardeva',
      'Barhaj',
      'Rudrapur',
    ],
    'Sultanpur': [
      'Sultanpur City',
      'Amethi',
      'Musafirkhana',
      'Kadipur',
      'Dostpur',
      'Lambhua',
    ],
    'Azamgarh': [
      'Azamgarh City',
      'Sathiaon',
      'Phulpur',
      'Lalganj',
      'Mehnagar',
      'Burhanpur',
      'Sagri',
    ],
    'Bijnor': [
      'Bijnor City',
      'Nagina',
      'Dhampur',
      'Najibabad',
      'Chandpur',
      'Seohara',
      'Nurpur',
    ],

    // ── Additional Bihar Districts ──
    'Gaya': [
      'Gaya City',
      'Bodhgaya',
      'Sherghati',
      'Tekari',
      'Wazirganj',
      'Manpur',
      'Dobhi',
    ],
    'Bhagalpur': [
      'Bhagalpur City',
      'Sultanganj',
      'Naugachhia',
      'Kahalgaon',
      'Sabour',
      'Pirpainti',
    ],
    'Muzaffarpur': [
      'Muzaffarpur City',
      'Kanti',
      'Saraiya',
      'Bochahan',
      'Marwan',
      'Gaighat',
    ],
    'Purnia': [
      'Purnia City',
      'Baisi',
      'Dhamdaha',
      'Kasba',
      'Banmankhi',
      'Rupauli',
    ],
    'Darbhanga': [
      'Darbhanga City',
      'Benipur',
      'Jale',
      'Baheri',
      'Keoti',
      'Hayaghat',
    ],
    'Bihar Sharif': [
      'Bihar Sharif City',
      'Rajgir',
      'Hilsa',
      'Ekangarsarai',
      'Noorsarai',
      'Islampur',
    ],
    'Arrah': [
      'Arrah City',
      'Jagdishpur',
      'Piro',
      'Koilwar',
      'Bihiya',
      'Sandesh',
    ],
    'Katihar': [
      'Katihar City',
      'Manihari',
      'Barsoi',
      'Korha',
      'Amdabad',
      'Falka',
    ],
    'Munger': [
      'Munger City',
      'Jamalpur',
      'Tarapur',
      'Bariarpur',
      'Kharagpur',
      'Dharhara',
    ],
    'Chhapra': [
      'Chhapra City',
      'Dighwara',
      'Marhowrah',
      'Sonpur',
      'Baniapur',
      'Amnour',
    ],
    'Hajipur': [
      'Hajipur City',
      'Lalganj',
      'Mahua',
      'Patepur',
      'Raghopur',
      'Vaishali',
    ],
    'Sasaram': [
      'Sasaram City',
      'Bikramganj',
      'Dehri',
      'Dinara',
      'Kochas',
      'Chenari',
    ],
    'Dehri': [
      'Dehri City',
      'Nasriganj',
      'Tilouthu',
      'Dalmianagar',
      'Karakat',
    ],
    'Siwan': [
      'Siwan City',
      'Maharajganj',
      'Raghunathpur',
      'Mairwa',
      'Darauli',
      'Goreakothi',
    ],
    'Motihari': [
      'Motihari City',
      'Raxaul',
      'Adapur',
      'Areraj',
      'Bettiah',
      'Sugauli',
      'Pakridayal',
    ],
    'Nawada': [
      'Nawada City',
      'Rajauli',
      'Hisua',
      'Warsaliganj',
      'Pakribarawan',
    ],
    'Bagaha': [
      'Bagaha City',
      'Narkatiaganj',
      'Bettiah',
      'Lauriya',
      'Chanpatia',
      'Mainatand',
    ],
    'Buxar': [
      'Buxar City',
      'Dumraon',
      'Rajpur',
      'Itarhi',
      'Chausa',
      'Simri',
    ],
    'Kishanganj': [
      'Kishanganj City',
      'Thakurganj',
      'Bahadurganj',
      'Pothia',
      'Kochadhaman',
    ],
    'Sitamarhi': [
      'Sitamarhi City',
      'Dumra',
      'Pupri',
      'Riga',
      'Bairgania',
      'Belsand',
    ],
    'Jamalpur': [
      'Jamalpur City',
      'Bariarpur',
      'Kharagpur',
      'Sultanganj',
      'Chausa',
    ],
    'Jehanabad': [
      'Jehanabad City',
      'Ghosi',
      'Kako',
      'Makhdumpur',
      'Ratni Faridpur',
    ],

    // ── Additional Gujarat Districts ──
    'Bhavnagar': [
      'Bhavnagar City',
      'Palitana',
      'Sihor',
      'Mahuva',
      'Talaja',
      'Ghogha',
      'Gariadhar',
    ],
    'Jamnagar': [
      'Jamnagar City',
      'Dhrol',
      'Jamjodhpur',
      'Kalavad',
      'Lalpur',
      'Jodiya',
    ],
    'Junagadh': [
      'Junagadh City',
      'Visavadar',
      'Manavadar',
      'Vanthali',
      'Keshod',
      'Mangrol',
      'Una',
    ],
    'Anand': [
      'Anand City',
      'Borsad',
      'Petlad',
      'Khambhat',
      'Umreth',
      'Sojitra',
      'Tarapur',
    ],
    'Nadiad': [
      'Nadiad City',
      'Mahemdabad',
      'Thasra',
      'Kapadvanj',
      'Balasinor',
      'Kathlal',
    ],
    'Morbi': [
      'Morbi City',
      'Halvad',
      'Wankaner',
      'Tankara',
      'Maliya Miyana',
    ],
    'Bharuch': [
      'Bharuch City',
      'Ankleshwar',
      'Jambusar',
      'Amod',
      'Vagra',
      'Jhagadia',
      'Hansot',
    ],
    'Vapi': [
      'Vapi City',
      'Daman',
      'Umbergaon',
      'Pardi',
      'Dharampur',
    ],
    'Navsari': [
      'Navsari City',
      'Bilimora',
      'Gandevi',
      'Chikhli',
      'Jalalpore',
      'Khergam',
    ],
    'Veraval': [
      'Veraval City',
      'Somnath',
      'Sutrapada',
      'Talala',
      'Kodinar',
    ],
    'Porbandar': [
      'Porbandar City',
      'Kutiyana',
      'Ranavav',
    ],
    'Godhra': [
      'Godhra City',
      'Dahod',
      'Halol',
      'Kalol',
      'Lunawada',
      'Shehera',
    ],
    'Palanpur': [
      'Palanpur City',
      'Deesa',
      'Dhanera',
      'Tharad',
      'Dantiwada',
      'Amirgadh',
    ],
    'Valsad': [
      'Valsad City',
      'Pardi',
      'Dharampur',
      'Umbergaon',
      'Kaprada',
    ],
    'Botad': [
      'Botad City',
      'Gadhada',
      'Ranpur',
      'Babra',
      'Barwala',
    ],
    'Amreli': [
      'Amreli City',
      'Rajula',
      'Savarkundla',
      'Lathi',
      'Babra',
      'Dhari',
      'Jafrabad',
    ],
    'Deesa': [
      'Deesa City',
      'Dhanera',
      'Tharad',
      'Bhabhar',
      'Kankrej',
      'Lakhani',
    ],
    'Jetpur': [
      'Jetpur City',
      'Dhoraji',
      'Upleta',
      'Jamkandorna',
      'Bhesan',
    ],
    'Gondal': [
      'Gondal City',
      'Kotda Sangani',
      'Jasdan',
      'Paddhari',
      'Lodhika',
    ],

    // ── Additional West Bengal Districts ──
    'Durgapur': [
      'Durgapur City',
      'Asansol',
      'Raniganj',
      'Andal',
      'Kulti',
      'Jamuria',
      'Pandabeswar',
    ],
    'Asansol': [
      'Asansol City',
      'Raniganj',
      'Burnpur',
      'Kulti',
      'Jamuria',
    ],
    'Siliguri': [
      'Siliguri City',
      'Jalpaiguri',
      'Mal',
      'Matiali',
      'Rajganj',
      'Maynaguri',
      'Dhupguri',
    ],
    'Baharampur': [
      'Baharampur City',
      'Jangipur',
      'Kandi',
      'Lalgola',
      'Domkal',
    ],
    'Habra': [
      'Habra City',
      'Barasat',
      'Baduria',
      'Basirhat',
      'Madhyamgram',
    ],
    'Kharagpur': [
      'Kharagpur City',
      'Jhargram',
      'Midnapore',
      'Debra',
      'Sabang',
      'Garhbeta',
    ],
    'Shantipur': [
      'Shantipur City',
      'Nabadwip',
      'Krishnanagar',
      'Chapra',
      'Tehatta',
    ],
    'Dankuni': [
      'Dankuni City',
      'Singur',
      'Haripal',
      'Chandannagar',
      'Serampore',
    ],
    'Dhulian': [
      'Dhulian City',
      'Jangipur',
      'Raghuraganj',
      'Samserganj',
    ],
    'Ranaghat': [
      'Ranaghat City',
      'Kalyani',
      'Chakdaha',
      'Haringhata',
      'Santipur',
    ],
    'Haldia': [
      'Haldia City',
      'Tamluk',
      'Contai',
      'Sutahata',
      'Nandigram',
    ],
    'Raiganj': [
      'Raiganj City',
      'Islampur',
      'Kaliaganj',
      'Balurghat',
      'Gangarampur',
    ],
    'Nabadwip': [
      'Nabadwip City',
      'Shantipur',
      'Krishnanagar',
      'Mayapur',
    ],
    'Medinipur': [
      'Medinipur City',
      'Sabang',
      'Ghatal',
      'Chandrakona',
      'Daspur',
      'Keshpur',
    ],
    'Jalpaiguri': [
      'Jalpaiguri City',
      'Alipurduar',
      'Falakata',
      'Madarihat',
      'Dhupguri',
      'Nagrakata',
    ],
    'Balurghat': [
      'Balurghat City',
      'Gangarampur',
      'Tapan',
      'Kushmandi',
      'Hili',
    ],
    'Basirhat': [
      'Basirhat City',
      'Haroa',
      'Sandeshkhali',
      'Hasnabad',
      'Hingalganj',
    ],
    'Darjeeling': [
      'Darjeeling City',
      'Kurseong',
      'Kalimpong',
      'Mirik',
      'Sukhiapokhri',
    ],

    // ── Additional Punjab Districts ──
    'Mohali': [
      'Mohali City',
      'Kharar',
      'Derabassi',
      'Lalru',
      'Kurali',
      'Banur',
    ],
    'Pathankot': [
      'Pathankot City',
      'Dalhousie',
      'Sujanpur',
      'Narot Jaimal Singh',
      'Shahpur Kandi',
    ],
    'Batala': [
      'Batala City',
      'Qadian',
      'Dera Baba Nanak',
      'Fatehgarh Churian',
      'Sri Hargobindpur',
    ],
    'Abohar': [
      'Abohar City',
      'Fazilka',
      'Jalalabad',
      'Arniwala',
      'Khuian Sarwar',
    ],
    'Malerkotla': [
      'Malerkotla City',
      'Ahmedgarh',
      'Amargarh',
      'Sangrur',
    ],
    'Khanna': [
      'Khanna City',
      'Samrala',
      'Machhiwara',
      'Doraha',
      'Sahnewal',
    ],
    'Phagwara': [
      'Phagwara City',
      'Nakodar',
      'Shahkot',
      'Kartarpur',
      'Phillaur',
    ],
    'Muktsar': [
      'Muktsar City',
      'Malout',
      'Gidderbaha',
      'Bariwala',
      'Lambi',
    ],
    'Barnala': [
      'Barnala City',
      'Tapa',
      'Bhadaur',
      'Sehna',
      'Dhanaula',
    ],
    'Rajpura': [
      'Rajpura City',
      'Nabha',
      'Samana',
      'Patiala',
      'Ghanaur',
    ],
    'Firozpur': [
      'Firozpur City',
      'Zira',
      'Guru Har Sahai',
      'Makhu',
      'Talwandi Bhai',
    ],
    'Sunam': [
      'Sunam City',
      'Moonak',
      'Lehra',
      'Bhawanigarh',
      'Dirba',
    ],
    'Nabha': [
      'Nabha City',
      'Amloh',
      'Rajpura',
      'Samana',
    ],
    'Tarn Taran': [
      'Tarn Taran City',
      'Patti',
      'Khem Karan',
      'Valtoha',
      'Naushera Pannuan',
    ],

    // ── Additional Haryana Districts ──
    'Panchkula': [
      'Panchkula City',
      'Kalka',
      'Barwala',
      'Raipur Rani',
      'Morni',
    ],
    'Sirsa': [
      'Sirsa City',
      'Dabwali',
      'Rania',
      'Ellenabad',
      'Baragudha',
      'Nathusari Chopta',
    ],
    'Bahadurgarh': [
      'Bahadurgarh City',
      'Jhajjar',
      'Beri',
      'Machhrauli',
      'Dighal',
    ],
    'Jind': [
      'Jind City',
      'Narwana',
      'Safidon',
      'Julana',
      'Uchana',
      'Alewa',
    ],
    'Thanesar': [
      'Thanesar City',
      'Kurukshetra',
      'Pehowa',
      'Shahabad',
      'Ladwa',
    ],
    'Kaithal': [
      'Kaithal City',
      'Cheeka',
      'Guhla',
      'Pundri',
      'Kalayat',
      'Rajaund',
    ],
    'Rewari': [
      'Rewari City',
      'Bawal',
      'Kosli',
      'Dharuhera',
      'Jatusana',
      'Nahar',
    ],
    'Palwal': [
      'Palwal City',
      'Hodal',
      'Hathin',
      'Hassanpur',
      'Prithla',
    ],
    'Hansi': [
      'Hansi City',
      'Barwala',
      'Uklana',
      'Bass',
      'Narnaund',
    ],
    'Mahendragarh': [
      'Mahendragarh City',
      'Narnaul',
      'Ateli',
      'Nangal Chaudhary',
      'Kanina',
    ],
    'Fatehabad': [
      'Fatehabad City',
      'Tohana',
      'Ratia',
      'Jakhal',
      'Bhattu Kalan',
    ],
    'Ratia': [
      'Ratia City',
      'Jakhal',
      'Tohana',
      'Fatehabad',
    ],
    'Tohana': [
      'Tohana City',
      'Ratia',
      'Jakhal',
      'Fatehabad',
    ],
    'Narnaul': [
      'Narnaul City',
      'Mahendragarh',
      'Ateli',
      'Nangal Chaudhary',
    ],
    'Charkhi Dadri': [
      'Charkhi Dadri City',
      'Loharu',
      'Siwani',
      'Tosham',
      'Baund Kalan',
    ],

    // ── Additional Rajasthan Districts ──
    'Bhilwara': [
      'Bhilwara City',
      'Gangapur',
      'Shahpura',
      'Mandal',
      'Jahazpur',
      'Asind',
      'Raipur',
    ],
    'Pali': [
      'Pali City',
      'Marwar Junction',
      'Sojat',
      'Jaitaran',
      'Desuri',
      'Bali',
      'Sumerpur',
    ],
    'Sri Ganganagar': [
      'Sri Ganganagar City',
      'Suratgarh',
      'Anupgarh',
      'Raisinghnagar',
      'Gharsana',
      'Padampur',
      'Karanpur',
    ],
    'Jhunjhunu': [
      'Jhunjhunu City',
      'Chirawa',
      'Pilani',
      'Udaipurwati',
      'Nawalgarh',
      'Khetri',
      'Mandawa',
    ],
    'Chittorgarh': [
      'Chittorgarh City',
      'Nimbahera',
      'Kapasan',
      'Begun',
      'Gangrar',
      'Rashmi',
      'Badi Sadri',
    ],
    'Tonk': [
      'Tonk City',
      'Deoli',
      'Malpura',
      'Newai',
      'Todaraisingh',
      'Uniara',
    ],
    'Beawar': [
      'Beawar City',
      'Kishangarh',
      'Nasirabad',
      'Sarwar',
      'Masuda',
    ],
    'Hanumangarh': [
      'Hanumangarh City',
      'Hanumangarh Junction',
      'Nohar',
      'Bhadra',
      'Pilibanga',
      'Rawatsar',
    ],
    'Gangapur City': [
      'Gangapur City',
      'Karauli',
      'Hindaun',
      'Todabhim',
      'Nadoti',
    ],
    'Dhaulpur': [
      'Dhaulpur City',
      'Bari',
      'Baseri',
      'Rajakhera',
      'Saipau',
    ],
    'Sawai Madhopur': [
      'Sawai Madhopur City',
      'Gangapur',
      'Bamanwas',
      'Khandar',
      'Bonli',
    ],
    'Barmer': [
      'Barmer City',
      'Balotra',
      'Siwana',
      'Gudhamalani',
      'Chohtan',
      'Pachpadra',
    ],
    'Nagaur': [
      'Nagaur City',
      'Ladnun',
      'Didwana',
      'Degana',
      'Makrana',
      'Merta',
      'Parbatsar',
    ],
    'Churu': [
      'Churu City',
      'Ratangarh',
      'Rajgarh',
      'Sujangarh',
      'Sardarshahar',
      'Taranagar',
    ],
    'Jhalawar': [
      'Jhalawar City',
      'Jhalrapatan',
      'Bhawani Mandi',
      'Pirawa',
      'Aklera',
    ],
    'Bundi': [
      'Bundi City',
      'Keshoraipatan',
      'Nainwa',
      'Indergarh',
      'Hindoli',
    ],

    // ── Additional MP Districts ──
    'Dewas': [
      'Dewas City',
      'Sonkatch',
      'Bagli',
      'Kannod',
      'Khategaon',
      'Tonk Khurd',
    ],
    'Satna': [
      'Satna City',
      'Maihar',
      'Amarpatan',
      'Rampur Baghelan',
      'Nagod',
      'Raghurajnagar',
    ],
    'Rewa': [
      'Rewa City',
      'Mauganj',
      'Hanumana',
      'Teonthar',
      'Sirmour',
      'Naigarhi',
    ],
    'Murwara': [
      'Murwara City',
      'Katni',
      'Vijayraghavgarh',
      'Rithi',
      'Bahoriband',
    ],
    'Singrauli': [
      'Singrauli City',
      'Waidhan',
      'Deosar',
      'Chitrangi',
      'Devsar',
    ],
    'Burhanpur': [
      'Burhanpur City',
      'Nepanagar',
      'Khaknar',
      'Shahpur',
    ],
    'Khandwa': [
      'Khandwa City',
      'Burhanpur',
      'Harda',
      'Mandhata',
      'Punasa',
      'Khalwa',
    ],
    'Morena': [
      'Morena City',
      'Ambah',
      'Porsa',
      'Joura',
      'Kailaras',
      'Sabalgarh',
    ],
    'Bhind': [
      'Bhind City',
      'Lahar',
      'Mehgaon',
      'Ater',
      'Gormi',
      'Machhand',
    ],
    'Chhindwara': [
      'Chhindwara City',
      'Pandhurna',
      'Sausar',
      'Amarwara',
      'Parasia',
      'Bichhua',
    ],
    'Guna': [
      'Guna City',
      'Ashokpura',
      'Raghogarh',
      'Chachoda',
      'Aron',
      'Bamori',
    ],
    'Shivpuri': [
      'Shivpuri City',
      'Karera',
      'Narwar',
      'Kolaras',
      'Pohari',
      'Pichhore',
    ],
    'Vidisha': [
      'Vidisha City',
      'Ganjbasoda',
      'Gyaraspur',
      'Lateri',
      'Sironj',
      'Nateran',
    ],
    'Damoh': [
      'Damoh City',
      'Hata',
      'Patharia',
      'Jabera',
      'Batiyagarh',
    ],
    'Chhatarpur': [
      'Chhatarpur City',
      'Nowgong',
      'Khajuraho',
      'Bijawar',
      'Maharajpur',
      'Laundi',
    ],
    'Mandsaur': [
      'Mandsaur City',
      'Neemuch',
      'Garoth',
      'Sitamau',
      'Malhargarh',
    ],
    'Neemuch': [
      'Neemuch City',
      'Manasa',
      'Jawad',
      'Singoli',
    ],
    'Hoshangabad': [
      'Hoshangabad City',
      'Itarsi',
      'Seonimalwa',
      'Babai',
      'Pipariya',
      'Bankhedi',
    ],

    // ── Additional Maharashtra Districts ──
    'Thane': [
      'Thane City',
      'Kalyan',
      'Dombivli',
      'Ulhasnagar',
      'Bhiwandi',
      'Ambarnath',
      'Shahapur',
    ],
    'Amravati': [
      'Amravati City',
      'Achalpur',
      'Paratwada',
      'Morshi',
      'Warud',
      'Daryapur',
      'Anjangaon',
    ],
    'Navi Mumbai': [
      'Navi Mumbai City',
      'Vashi',
      'Nerul',
      'Panvel',
      'Belapur',
      'Kharghar',
      'Airoli',
    ],
    'Akola': [
      'Akola City',
      'Akot',
      'Telhara',
      'Balapur',
      'Patur',
      'Murtijapur',
      'Barshitakli',
    ],
    'Dhule': [
      'Dhule City',
      'Shirpur',
      'Dondaicha',
      'Sakri',
      'Shindkheda',
      'Nardana',
    ],
    'Parbhani': [
      'Parbhani City',
      'Gangakhed',
      'Pathri',
      'Jintur',
      'Selu',
      'Sonpeth',
      'Purna',
    ],
    'Jalna': [
      'Jalna City',
      'Ambad',
      'Partur',
      'Badnapur',
      'Mantha',
      'Bhokardan',
    ],
    'Bhiwandi': [
      'Bhiwandi City',
      'Shahapur',
      'Wada',
      'Kalyan',
      'Murbad',
    ],
    'Nanded': [
      'Nanded City',
      'Deglur',
      'Mukhed',
      'Kandhar',
      'Kinwat',
      'Loha',
      'Hadgaon',
    ],
    'Ratnagiri': [
      'Ratnagiri City',
      'Chiplun',
      'Dapoli',
      'Lanja',
      'Rajapur',
      'Sangameshwar',
      'Guhagar',
    ],
    'Osmanabad': [
      'Osmanabad City',
      'Tuljapur',
      'Omerga',
      'Paranda',
      'Bhum',
      'Kalamb',
    ],
    'Wardha': [
      'Wardha City',
      'Hinganghat',
      'Arvi',
      'Deoli',
      'Ashti',
      'Seloo',
    ],

    // ── Additional Karnataka Districts ──
    'Bengaluru': [
      'Bengaluru City',
      'Yelahanka',
      'Anekal',
      'Devanahalli',
      'Doddaballapur',
      'Hoskote',
      'Nelamangala',
    ],
    'Hubli': [
      'Hubli City',
      'Dharwad',
      'Alnavar',
      'Kalghatgi',
      'Navalgund',
      'Kundgol',
    ],
    'Mangalore': [
      'Mangalore City',
      'Bantwal',
      'Puttur',
      'Sullia',
      'Belthangady',
      'Moodabidri',
    ],
    'Gulbarga': [
      'Gulbarga City',
      'Aland',
      'Afzalpur',
      'Chincholi',
      'Jevargi',
      'Sedam',
      'Shahabad',
    ],
    'Davanagere': [
      'Davanagere City',
      'Harihar',
      'Jagalur',
      'Channagiri',
      'Honnali',
    ],
    'Bijapur': [
      'Bijapur City',
      'Bagewadi',
      'Muddebihal',
      'Sindgi',
      'Indi',
      'Basavana Bagewadi',
    ],
    'Raichur': [
      'Raichur City',
      'Sindhanur',
      'Manvi',
      'Devadurga',
      'Lingasugur',
    ],
    'Hospet': [
      'Hospet City',
      'Bellary',
      'Sandur',
      'Kudligi',
      'Siruguppa',
    ],
    'Gadag': [
      'Gadag City',
      'Nargund',
      'Ron',
      'Shirhatti',
      'Mundargi',
    ],
    'Udupi': [
      'Udupi City',
      'Kundapura',
      'Karkala',
      'Brahmavar',
      'Byndoor',
    ],
    'Robertson Pet': [
      'Robertson Pet',
      'KGF',
      'Bangarapet',
      'Kolar',
      'Mulbagal',
    ],
    'Bhadravati': [
      'Bhadravati City',
      'Shimoga',
      'Sagar',
      'Hosanagara',
    ],
    'Chitradurga': [
      'Chitradurga City',
      'Challakere',
      'Hiriyur',
      'Holalkere',
      'Hosadurga',
      'Molakalmuru',
    ],
    'Mandya': [
      'Mandya City',
      'Nagamangala',
      'Maddur',
      'Malavalli',
      'Srirangapatna',
      'Pandavapura',
    ],
    'Chikmagalur': [
      'Chikmagalur City',
      'Kadur',
      'Tarikere',
      'Koppa',
      'Sringeri',
      'Mudigere',
    ],
    'Bagalkot': [
      'Bagalkot City',
      'Badami',
      'Mudhol',
      'Jamkhandi',
      'Hunagund',
      'Bilagi',
    ],
    'Ranebennur': [
      'Ranebennur City',
      'Haveri',
      'Byadgi',
      'Savanur',
      'Hanagal',
      'Shiggaon',
    ],

    // ── Uttarakhand Districts ──
    'Dehradun': [
      'Dehradun City',
      'Rishikesh',
      'Doiwala',
      'Vikasnagar',
      'Mussoorie',
      'Sahaspur',
    ],
    'Haridwar': [
      'Haridwar City',
      'Roorkee',
      'Laksar',
      'Manglaur',
      'Narsan',
      'Bhagwanpur',
    ],
    'Rishikesh': [
      'Rishikesh City',
      'Muni Ki Reti',
      'Jonk',
      'Narendranagar',
    ],
    'Roorkee': [
      'Roorkee City',
      'Laksar',
      'Jwalapur',
      'Landhaura',
      'Bhagwanpur',
    ],
    'Haldwani': [
      'Haldwani City',
      'Kathgodam',
      'Lalkuan',
      'Rudrapur',
      'Kichha',
      'Gadarpur',
    ],
    'Kashipur': [
      'Kashipur City',
      'Bazpur',
      'Jaspur',
      'Ramnagar',
      'Kaladhungi',
    ],
    'Rudrapur': [
      'Rudrapur City',
      'Kichha',
      'Sitarganj',
      'Gadarpur',
      'Nanakmatta',
    ],
    'Nainital': [
      'Nainital City',
      'Bhimtal',
      'Bhowali',
      'Ramgarh',
      'Mukteshwar',
    ],
    'Almora': [
      'Almora City',
      'Ranikhet',
      'Bhikiyasain',
      'Someshwar',
      'Dwarahat',
    ],
    'Pithoragarh': [
      'Pithoragarh City',
      'Dharchula',
      'Gangolihat',
      'Berinag',
      'Munsyari',
    ],

    // ── Chhattisgarh Districts ──
    'Raipur': [
      'Raipur City',
      'Arang',
      'Abhanpur',
      'Tilda-Neora',
      'Simga',
      'Dharsiwa',
    ],
    'Bhilai': [
      'Bhilai City',
      'Durg',
      'Patan',
      'Dhamdha',
      'Ahiwara',
    ],
    'Bilaspur': [
      'Bilaspur City',
      'Takhatpur',
      'Masturi',
      'Kota',
      'Lormi',
      'Ratanpur',
    ],
    'Korba': [
      'Korba City',
      'Katghora',
      'Pali',
      'Kartala',
      'Pondi-Uproda',
    ],
    'Durg': [
      'Durg City',
      'Bhilai',
      'Rajnandgaon',
      'Patan',
      'Dhamdha',
    ],
    'Rajnandgaon': [
      'Rajnandgaon City',
      'Dongargarh',
      'Khairagarh',
      'Chhuikhadan',
      'Mohla',
    ],
    'Raigarh': [
      'Raigarh City',
      'Sarangarh',
      'Gharghoda',
      'Tamnar',
      'Dharamjaigarh',
    ],
    'Jagdalpur': [
      'Jagdalpur City',
      'Dantewada',
      'Sukma',
      'Kondagaon',
      'Narayanpur',
    ],
    'Ambikapur': [
      'Ambikapur City',
      'Wadrafnagar',
      'Rajpur',
      'Sitapur',
      'Batauli',
    ],

    // ── Jharkhand Districts ──
    'Ranchi': [
      'Ranchi City',
      'Kanke',
      'Namkum',
      'Ratu',
      'Bundu',
      'Mandar',
    ],
    'Jamshedpur': [
      'Jamshedpur City',
      'Adityapur',
      'Gamharia',
      'Jugsalai',
      'Mango',
    ],
    'Dhanbad': [
      'Dhanbad City',
      'Jharia',
      'Sindri',
      'Katras',
      'Govindpur',
    ],
    'Bokaro': [
      'Bokaro City',
      'Chas',
      'Gomia',
      'Chandrapura',
      'Bermo',
    ],
    'Deoghar': [
      'Deoghar City',
      'Madhupur',
      'Jasidih',
      'Karmatand',
      'Devipur',
    ],
    'Hazaribagh': [
      'Hazaribagh City',
      'Barhi',
      'Ichak',
      'Katkamsandi',
      'Churchu',
    ],
    'Giridih': [
      'Giridih City',
      'Dumri',
      'Tisri',
      'Bengabad',
      'Jamua',
    ],
    'Ramgarh': [
      'Ramgarh City',
      'Patratu',
      'Mandu',
      'Gola',
      'Dulmi',
    ],

    // ── Andhra Pradesh Districts ──
    'Amaravati': ['Amaravati City', 'Mangalagiri', 'Thullur', 'Tadepalli', 'Sattenapalli'],
    'Visakhapatnam': ['Visakhapatnam City', 'Gajuwaka', 'Anakapalle', 'Bheemunipatnam', 'Pendurthi', 'Madhurawada'],
    'Vijayawada': ['Vijayawada City', 'Gannavaram', 'Nunna', 'Kanchikacharla', 'Ibrahimpatnam'],
    'Guntur': ['Guntur City', 'Tenali', 'Narasaraopet', 'Mangalagiri', 'Bapatla', 'Sattenapalli'],
    'Nellore': ['Nellore City', 'Kavali', 'Gudur', 'Sullurpeta', 'Venkatagiri', 'Atmakur'],
    'Kurnool': ['Kurnool City', 'Adoni', 'Yemmiganur', 'Nandyal', 'Dhone', 'Allagadda'],
    'Rajahmundry': ['Rajahmundry City', 'Kakinada', 'Amalapuram', 'Mandapeta', 'Ramachandrapuram'],
    'Kakinada': ['Kakinada City', 'Samalkot', 'Peddapuram', 'Gollaprolu', 'Tuni'],
    'Tirupati': ['Tirupati City', 'Tirumala', 'Srikalahasti', 'Chandragiri', 'Renigunta'],
    'Kadapa': ['Kadapa City', 'Proddatur', 'Rajampet', 'Jammalamadugu', 'Pulivendula', 'Badvel'],
    'Anantapur': ['Anantapur City', 'Hindupur', 'Guntakal', 'Tadpatri', 'Dharmavaram', 'Penukonda'],
    'Vizianagaram': ['Vizianagaram City', 'Bobbili', 'Parvathipuram', 'Rajam', 'Nellimarla'],
    'Eluru': ['Eluru City', 'Tadepalligudem', 'Nidadavolu', 'Jangareddigudem', 'Tanuku'],
    'Ongole': ['Ongole City', 'Chirala', 'Markapur', 'Kandukur', 'Darsi', 'Addanki'],
    'Nandyal': ['Nandyal City', 'Nandikotkur', 'Kurnool', 'Allagadda', 'Banaganapalle'],
    'Machilipatnam': ['Machilipatnam City', 'Gudivada', 'Pedana', 'Avanigadda', 'Bantumilli'],
    'Adoni': ['Adoni City', 'Mantralayam', 'Yemmiganur', 'Kosigi', 'Pattikonda'],
    'Tenali': ['Tenali City', 'Repalle', 'Bapatla', 'Chirala', 'Duggirala'],
    'Chittoor': ['Chittoor City', 'Madanapalle', 'Punganur', 'Palamaner', 'Kuppam', 'Nagari'],
    'Hindupur': ['Hindupur City', 'Penukonda', 'Lepakshi', 'Madakasira', 'Roddam'],
    'Proddatur': ['Proddatur City', 'Rajampet', 'Mydukur', 'Ondipuli', 'Duvvur'],
    'Bhimavaram': ['Bhimavaram City', 'Palacole', 'Narasapuram', 'Undi', 'Akividu'],
    'Madanapalle': ['Madanapalle City', 'Punganur', 'Vayalpad', 'Pileru', 'Nimmanapalle'],
    'Guntakal': ['Guntakal City', 'Gooty', 'Uravakonda', 'Pamidi', 'Rayadurg'],
    'Srikakulam': ['Srikakulam City', 'Palasa', 'Amadalavalasa', 'Ichapuram', 'Narasannapeta'],

    // ── Arunachal Pradesh Districts ──
    'Itanagar': ['Itanagar City', 'Naharlagun', 'Banderdewa', 'Nirjuli', 'Chimpu'],
    'Naharlagun': ['Naharlagun City', 'Itanagar', 'Banderdewa', 'Nirjuli', 'Doimukh'],
    'Pasighat': ['Pasighat City', 'Mebo', 'Nari', 'Pangin', 'Ruksin'],
    'Tawang': ['Tawang City', 'Jang', 'Lumla', 'Zemithang', 'Mukto'],
    'Ziro': ['Ziro City', 'Hapoli', 'Hong', 'Tarin', 'Yazali'],
    'Bomdila': ['Bomdila City', 'Dirang', 'Kalaktang', 'Rupa', 'Singchung'],
    'Along': ['Along City', 'Basar', 'Likabali', 'Daporijo', 'Mechuka'],
    'Tezu': ['Tezu City', 'Namsai', 'Chongkham', 'Wakro', 'Hayuliang'],
    'Anini': ['Anini City', 'Mipi', 'Dambuk', 'Roing', 'Hunli'],
    'Daporijo': ['Daporijo City', 'Dumporijo', 'Taliha', 'Nacho', 'Siyum'],
    'Namsai': ['Namsai City', 'Chongkham', 'Lekang', 'Piyong', 'Lathao'],
    'Changlang': ['Changlang City', 'Miao', 'Bordumsa', 'Diyun', 'Nampong'],
    'Khonsa': ['Khonsa City', 'Longding', 'Deomali', 'Laju', 'Kanubari'],
    'Yingkiong': ['Yingkiong City', 'Tuting', 'Mariyang', 'Jengging', 'Gelling'],
    'Roing': ['Roing City', 'Dambuk', 'Hunli', 'Anini', 'Desali'],

    // ── Assam Districts ──
    'Guwahati': ['Guwahati City', 'Dispur', 'Chandmari', 'Jalukbari', 'Panbazar', 'Khanapara'],
    'Silchar': ['Silchar City', 'Lakhipur', 'Katigorah', 'Udharbond', 'Sonai'],
    'Dibrugarh': ['Dibrugarh City', 'Naharkatia', 'Duliajan', 'Moran', 'Khowang', 'Tengakhat'],
    'Jorhat': ['Jorhat City', 'Titabor', 'Mariani', 'Teok', 'Selenghat'],
    'Nagaon': ['Nagaon City', 'Hojai', 'Lanka', 'Kaliabor', 'Raha', 'Samaguri'],
    'Tinsukia': ['Tinsukia City', 'Digboi', 'Margherita', 'Doomdooma', 'Makum', 'Sadiya'],
    'Tezpur': ['Tezpur City', 'Rangapara', 'Dhekiajuli', 'Gohpur', 'Biswanath Chariali'],
    'Bongaigaon': ['Bongaigaon City', 'Abhayapuri', 'Bijni', 'Srijangram', 'North Salmara'],
    'Diphu': ['Diphu City', 'Bokajan', 'Howraghat', 'Dokmoka', 'Rongkhang'],
    'North Lakhimpur': ['North Lakhimpur City', 'Dhakuakhana', 'Bihpuria', 'Narayanpur', 'Kadam'],
    'Dhubri': ['Dhubri City', 'Gauripur', 'Bilasipara', 'Golakganj', 'Kokrajhar'],
    'Karimganj': ['Karimganj City', 'Badarpur', 'Patharkandi', 'Ratabari', 'Nilambazar'],
    'Sivasagar': ['Sivasagar City', 'Nazira', 'Sonari', 'Demow', 'Simaluguri', 'Gaurisagar'],
    'Goalpara': ['Goalpara City', 'Lakhipur', 'Dudhnai', 'Krishnai', 'Matia'],
    'Barpeta': ['Barpeta City', 'Howly', 'Sarthebari', 'Bajali', 'Patacharkuchi'],
    'Mangaldoi': ['Mangaldoi City', 'Kharupetia', 'Sipajhar', 'Dalgaon', 'Pathorighat'],
    'Nalbari': ['Nalbari City', 'Tihu', 'Barama', 'Mukalmua', 'Barkhetri'],
    'Rangia': ['Rangia City', 'Nalbari', 'Barpeta Road', 'Hajo', 'Boko'],
    'Lumding': ['Lumding City', 'Hojai', 'Lanka', 'Doboka', 'Maibong'],
    'Haflong': ['Haflong City', 'Maibong', 'Mahur', 'Jatinga', 'Umrangso'],

    // ── Goa Districts ──
    'Panaji': ['Panaji City', 'Dona Paula', 'Taleigao', 'Ribandar', 'Old Goa', 'Caranzalem'],
    'Margao': ['Margao City', 'Colva', 'Benaulim', 'Fatorda', 'Cuncolim', 'Navelim'],
    'Vasco da Gama': ['Vasco City', 'Dabolim', 'Zuarinagar', 'Bogda', 'Chicalim', 'Sancoale'],
    'Mapusa': ['Mapusa City', 'Calangute', 'Candolim', 'Assagao', 'Anjuna', 'Moira'],
    'Ponda': ['Ponda City', 'Mardol', 'Priol', 'Farmagudi', 'Bandora', 'Curti'],
    'Bicholim': ['Bicholim City', 'Sanquelim', 'Pale', 'Amona', 'Mulgao'],
    'Curchorem': ['Curchorem City', 'Sanvordem', 'Quepem', 'Balli', 'Xeldem'],
    'Sanquelim': ['Sanquelim City', 'Bicholim', 'Valpoi', 'Pale', 'Codal'],
    'Cuncolim': ['Cuncolim City', 'Balli', 'Velim', 'Assolna', 'Chinchinim'],
    'Quepem': ['Quepem City', 'Curchorem', 'Xeldem', 'Balli', 'Ambaulim'],
    'Sanguem': ['Sanguem City', 'Rivona', 'Netravali', 'Usgao', 'Neturlim'],
    'Canacona': ['Canacona City', 'Palolem', 'Agonda', 'Poinguinim', 'Chaudi'],
    'Pernem': ['Pernem City', 'Arambol', 'Morjim', 'Mandrem', 'Aswem'],
    'Valpoi': ['Valpoi City', 'Sattari', 'Honda', 'Thane', 'Pissurlem'],
    'Mormugao': ['Mormugao City', 'Vasco', 'Dabolim', 'Sancoale', 'Chicalim'],

    // ── Himachal Pradesh Districts ──
    'Shimla': ['Shimla City', 'Kufri', 'Mashobra', 'Theog', 'Rampur Bushahr', 'Rohru'],
    'Dharamshala': ['Dharamshala City', 'McLeod Ganj', 'Kangra', 'Nurpur', 'Palampur', 'Baijnath'],
    'Solan': ['Solan City', 'Nalagarh', 'Kasauli', 'Parwanoo', 'Baddi', 'Arki'],
    'Mandi': ['Mandi City', 'Sundernagar', 'Jogindernagar', 'Rewalsar', 'Gohar', 'Baldwara'],
    'Palampur': ['Palampur City', 'Baijnath', 'Jaisinghpur', 'Dharmpur', 'Lambagaon'],
    'Baddi': ['Baddi City', 'Barotiwala', 'Nalagarh', 'Parwanoo', 'Ramshahar'],
    'Nahan': ['Nahan City', 'Paonta Sahib', 'Rajgarh', 'Sarahan', 'Renuka'],
    'Kullu': ['Kullu City', 'Manali', 'Bhuntar', 'Banjar', 'Naggar', 'Manikaran'],
    'Manali': ['Manali City', 'Old Manali', 'Vashisht', 'Solang', 'Naggar'],
    'Hamirpur': ['Hamirpur City', 'Barsar', 'Nadaun', 'Bhoranj', 'Sujanpur Tihra'],
    'Una': ['Una City', 'Amb', 'Gagret', 'Bangana', 'Haroli', 'Mehatpur'],
    'Chamba': ['Chamba City', 'Dalhousie', 'Banikhet', 'Churah', 'Pangi', 'Bharmour'],
    'Bilaspur (HP)': ['Bilaspur City', 'Ghumarwin', 'Naina Devi', 'Jhandutta', 'Swarghat'],
    'Kangra': ['Kangra City', 'Dharamshala', 'Palampur', 'Nurpur', 'Jawali', 'Dehra Gopipur'],
    'Dalhousie': ['Dalhousie City', 'Khajjiar', 'Chamba', 'Banikhet', 'Salooni'],
    'Paonta Sahib': ['Paonta Sahib City', 'Nahan', 'Rajgarh', 'Kala Amb', 'Shillai'],
    'Sundernagar': ['Sundernagar City', 'Mandi', 'Karsog', 'Jogindernagar', 'Aut'],
    'Parwanoo': ['Parwanoo City', 'Kasauli', 'Baddi', 'Kalka', 'Solan'],
    'Santokhgarh': ['Santokhgarh City', 'Mandi', 'Sundernagar', 'Ner Chowk'],
    'Theog': ['Theog City', 'Kotkhai', 'Mashobra', 'Narkanda', 'Kufri'],

    // ── Kerala Districts ──
    'Thiruvananthapuram': ['Thiruvananthapuram City', 'Neyyattinkara', 'Nedumangad', 'Attingal', 'Varkala', 'Kovalam'],
    'Kochi': ['Kochi City', 'Ernakulam', 'Fort Kochi', 'Mattancherry', 'Aluva', 'Kalamassery', 'Thrikkakara'],
    'Kozhikode': ['Kozhikode City', 'Vadakara', 'Koyilandy', 'Feroke', 'Ramanattukara', 'Beypore'],
    'Thrissur': ['Thrissur City', 'Guruvayur', 'Chalakudy', 'Irinjalakuda', 'Kodungallur', 'Chavakkad'],
    'Kollam': ['Kollam City', 'Punalur', 'Karunagappally', 'Kottarakkara', 'Paravur', 'Chathannoor'],
    'Palakkad': ['Palakkad City', 'Ottapalam', 'Shoranur', 'Alathur', 'Chittur', 'Mannarkkad'],
    'Alappuzha': ['Alappuzha City', 'Cherthala', 'Kayamkulam', 'Mavelikkara', 'Haripad', 'Ambalapuzha'],
    'Kannur': ['Kannur City', 'Thalassery', 'Payyanur', 'Taliparamba', 'Iritty', 'Mattannur'],
    'Kottayam': ['Kottayam City', 'Changanassery', 'Pala', 'Ettumanoor', 'Vaikom', 'Erattupetta'],
    'Malappuram': ['Malappuram City', 'Manjeri', 'Perinthalmanna', 'Ponnani', 'Tirur', 'Nilambur'],
    'Kasaragod': ['Kasaragod City', 'Kanhangad', 'Nileshwar', 'Cheruvathur', 'Uppala', 'Bekal'],
    'Pathanamthitta': ['Pathanamthitta City', 'Adoor', 'Thiruvalla', 'Pandalam', 'Ranni', 'Kozhencherry'],
    'Idukki': ['Idukki City', 'Thodupuzha', 'Munnar', 'Adimali', 'Kattappana', 'Nedumkandam'],
    'Wayanad': ['Wayanad City', 'Kalpetta', 'Sulthan Bathery', 'Mananthavady', 'Meenangadi', 'Panamaram'],
    'Ernakulam': ['Ernakulam City', 'Aluva', 'Angamaly', 'Perumbavoor', 'Muvattupuzha', 'North Paravur'],
    'Thalassery': ['Thalassery City', 'Mahe', 'Kannur', 'Iritty', 'Kuthuparamba'],
    'Kayamkulam': ['Kayamkulam City', 'Haripad', 'Mavelikkara', 'Cherthala', 'Ambalapuzha'],
    'Vatakara': ['Vatakara City', 'Nadapuram', 'Koyilandy', 'Thodannur', 'Mahe'],
    'Manjeri': ['Manjeri City', 'Perinthalmanna', 'Malappuram', 'Nilambur', 'Wandoor'],
    'Ottapalam': ['Ottapalam City', 'Shoranur', 'Pattambi', 'Thrithala', 'Sreekrishnapuram'],

    // ── Manipur Districts ──
    'Imphal': ['Imphal City', 'Lamphel', 'Singjamei', 'Porompat', 'Khurai', 'Uripok'],
    'Thoubal': ['Thoubal City', 'Kakching', 'Lilong', 'Wangjing', 'Yairipok', 'Sugnu'],
    'Bishnupur': ['Bishnupur City', 'Moirang', 'Nambol', 'Ningthoukhong', 'Kumbi'],
    'Churachandpur': ['Churachandpur City', 'Singhat', 'Thanlon', 'Henglep', 'Tipaimukh'],
    'Kakching': ['Kakching City', 'Waikhong', 'Pallel', 'Sugnu', 'Hiyanglam'],
    'Ukhrul': ['Ukhrul City', 'Jessami', 'Kamjong', 'Phungyar', 'Chingai'],
    'Senapati': ['Senapati City', 'Kangpokpi', 'Mao', 'Maram', 'Saikul'],
    'Tamenglong': ['Tamenglong City', 'Noney', 'Khoupum', 'Tousem', 'Tamei'],
    'Chandel': ['Chandel City', 'Moreh', 'Machi', 'Chakpikarong', 'Tengnoupal'],
    'Jiribam': ['Jiribam City', 'Borobekra', 'Jiri', 'Nungba'],
    'Moirang': ['Moirang City', 'Bishnupur', 'Ningthoukhong', 'Kumbi', 'Toubul'],
    'Mayang Imphal': ['Mayang Imphal City', 'Wangoi', 'Kangchup', 'Patsoi'],
    'Nambol': ['Nambol City', 'Bishnupur', 'Oinam', 'Moirang'],
    'Wangoi': ['Wangoi City', 'Kangchup', 'Mayang Imphal', 'Patsoi'],
    'Yairipok': ['Yairipok City', 'Wangjing', 'Thoubal', 'Lilong'],

    // ── Meghalaya Districts ──
    'Shillong': ['Shillong City', 'Laitumkhrah', 'Police Bazar', 'Nongthymmai', 'Mawlai', 'Nongpoh'],
    'Tura': ['Tura City', 'Phulbari', 'Dalu', 'Mahendraganj', 'Resubelpara'],
    'Nongstoin': ['Nongstoin City', 'Mairang', 'Nongkhlaw', 'Mawshynrut', 'Ranikor'],
    'Jowai': ['Jowai City', 'Nartiang', 'Dawki', 'Amlarem', 'Laskein'],
    'Baghmara': ['Baghmara City', 'Dalu', 'Siju', 'Chokpot', 'Wangala'],
    'Williamnagar': ['Williamnagar City', 'Samanda', 'Rongjeng', 'Dadenggre'],
    'Resubelpara': ['Resubelpara City', 'Mendipathar', 'Bajengdoba', 'Tikrikilla'],
    'Ampati': ['Ampati City', 'Mahendraganj', 'Betasing', 'Fulbari'],
    'Mairang': ['Mairang City', 'Nongstoin', 'Nongkhlaw', 'Mawkyrwat'],
    'Khliehriat': ['Khliehriat City', 'Saipung', 'Nongpoh', 'Thadlaskein'],
    'Cherrapunji': ['Cherrapunji City', 'Sohra', 'Mawsynram', 'Mawphlang'],
    'Dawki': ['Dawki City', 'Jowai', 'Laskein', 'Tamabil'],
    'Nongpoh': ['Nongpoh City', 'Umroi', 'Byrnihat', 'Nongkhyllem'],
    'Madanriting': ['Madanriting City', 'Laitumkhrah', 'Shillong'],

    // ── Mizoram Districts ──
    'Aizawl': ['Aizawl City', 'Durtlang', 'Bawngkawn', 'Zemabawk', 'Chaltlang', 'Kulikawn'],
    'Lunglei': ['Lunglei City', 'Hnahthial', 'Tlabung', 'Demagiri', 'Bunghmun'],
    'Champhai': ['Champhai City', 'Khawzawl', 'Biate', 'Ngopa', 'Vaphai'],
    'Serchhip': ['Serchhip City', 'Thenzawl', 'East Lungdar', 'North Vanlaiphai'],
    'Kolasib': ['Kolasib City', 'Bairabi', 'Kawnpui', 'Bilkhawthlir', 'Vairengte'],
    'Saiha': ['Saiha City', 'Tuipang', 'Sangau', 'Lawngtlai', 'Chawngte'],
    'Lawngtlai': ['Lawngtlai City', 'Chawngte', 'Bungtlang', 'Sangau'],
    'Mamit': ['Mamit City', 'Zawlnuam', 'Reiek', 'West Phaileng'],
    'Khawzawl': ['Khawzawl City', 'Champhai', 'Ngopa', 'Biate'],
    'Hnahthial': ['Hnahthial City', 'Lunglei', 'Thingsai', 'Rawpui'],
    'Saitual': ['Saitual City', 'Keifang', 'Phullen', 'North Vanlaiphai'],
    'Bairabi': ['Bairabi City', 'Kolasib', 'Kawnpui', 'Vairengte'],
    'Tlabung': ['Tlabung City', 'Lunglei', 'Demagiri', 'Hnahthial'],
    'North Vanlaiphai': ['North Vanlaiphai City', 'Thenzawl', 'Serchhip', 'Saitual'],
    'Thenzawl': ['Thenzawl City', 'Serchhip', 'East Lungdar', 'Buarpui'],

    // ── Nagaland Districts ──
    'Kohima': ['Kohima City', 'Chiephobozou', 'Tseminyu', 'Jakhama', 'Viswema', 'Botsa'],
    'Dimapur': ['Dimapur City', 'Chumukedima', 'Medziphema', 'Dhansiripar', 'Niuland'],
    'Mokokchung': ['Mokokchung City', 'Ongpangkong', 'Tuli', 'Changtongya', 'Longchem'],
    'Tuensang': ['Tuensang City', 'Shamator', 'Noklak', 'Longkhim', 'Chare'],
    'Wokha': ['Wokha City', 'Sanis', 'Bhandari', 'Changsu', 'Ralan'],
    'Zunheboto': ['Zunheboto City', 'Aghunato', 'Satakha', 'Suruhuto', 'Tokiye'],
    'Phek': ['Phek City', 'Pfutsero', 'Chozuba', 'Meluri', 'Chetheba'],
    'Mon': ['Mon City', 'Tobu', 'Aboi', 'Tizit', 'Chen'],
    'Kiphire': ['Kiphire City', 'Pungro', 'Seyochung', 'Sitimi', 'Longmatra'],
    'Longleng': ['Longleng City', 'Tamlu', 'Sakshi', 'Yachem'],
    'Peren': ['Peren City', 'Jalukie', 'Tening', 'Athibung', 'Nsong'],
    'Noklak': ['Noklak City', 'Shamator', 'Tuensang', 'Pangsha'],
    'Tseminyu': ['Tseminyu City', 'Kohima', 'Chiephobozou', 'Pfuchama'],
    'Chumukedima': ['Chumukedima City', 'Dimapur', 'Medziphema', 'Niuland'],
    'Shamator': ['Shamator City', 'Noklak', 'Tuensang', 'Chare'],

    // ── Odisha Districts ──
    'Bhubaneswar': ['Bhubaneswar City', 'Jatni', 'Khurda', 'Balipatna', 'Balianta', 'Pipili'],
    'Cuttack': ['Cuttack City', 'Choudwar', 'Jagatpur', 'Athagarh', 'Banki', 'Narasinghpur'],
    'Rourkela': ['Rourkela City', 'Rajgangpur', 'Birmitrapur', 'Bisra', 'Brahmani'],
    'Berhampur': ['Berhampur City', 'Gopalpur', 'Chhatrapur', 'Hinjilicut', 'Aska', 'Digapahandi'],
    'Sambalpur': ['Sambalpur City', 'Burla', 'Hirakud', 'Kuchinda', 'Rairakhol', 'Dhankauda'],
    'Puri': ['Puri City', 'Konark', 'Pipili', 'Nimapara', 'Satapada', 'Brahmagiri'],
    'Balasore': ['Balasore City', 'Jaleswar', 'Soro', 'Nilgiri', 'Simulia', 'Basta'],
    'Bhadrak': ['Bhadrak City', 'Dhamnagar', 'Basudevpur', 'Chandbali', 'Tihidi'],
    'Baripada': ['Baripada City', 'Rairangpur', 'Karanjia', 'Udala', 'Jashipur'],
    'Jharsuguda': ['Jharsuguda City', 'Belpahar', 'Brajarajnagar', 'Kolabira', 'Lakhanpur'],
    'Jeypore': ['Jeypore City', 'Koraput', 'Sunabeda', 'Malkangiri', 'Borigumma'],
    'Angul': ['Angul City', 'Talcher', 'Athamallik', 'Pallahara', 'Chhendipada'],
    'Barbil': ['Barbil City', 'Joda', 'Keonjhar', 'Champua', 'Banspal'],
    'Paradip': ['Paradip City', 'Kujang', 'Ersama', 'Tirtol', 'Jagatsinghpur'],
    'Kendrapara': ['Kendrapara City', 'Pattamundai', 'Rajnagar', 'Marshaghai', 'Derabish'],
    'Sunabeda': ['Sunabeda City', 'Koraput', 'Jeypore', 'Semiliguda', 'Laxmipur'],
    'Bargarh': ['Bargarh City', 'Padmapur', 'Attabira', 'Barpali', 'Ambabhona'],
    'Rayagada': ['Rayagada City', 'Gunupur', 'Gudari', 'Kashipur', 'Bissamcuttack'],
    'Koraput': ['Koraput City', 'Jeypore', 'Sunabeda', 'Semiliguda', 'Pottangi'],
    'Phulbani': ['Phulbani City', 'Baliguda', 'G. Udayagiri', 'Tikabali', 'Daringbadi'],

    // ── Sikkim Districts ──
    'Gangtok': ['Gangtok City', 'Tadong', 'Ranipool', 'Singtam', 'Rangpo', 'Rumtek'],
    'Namchi': ['Namchi City', 'Jorethang', 'Ravangla', 'Yangang', 'Damthang'],
    'Gyalshing': ['Gyalshing City', 'Pelling', 'Yuksom', 'Dentam', 'Legship', 'Tashiding'],
    'Mangan': ['Mangan City', 'Chungthang', 'Lachen', 'Lachung', 'Singhik'],
    'Rangpo': ['Rangpo City', 'Singtam', 'Rongli', 'Rhenock', 'Pakyong'],
    'Singtam': ['Singtam City', 'Rangpo', 'Gangtok', 'Makha', 'Sirwani'],
    'Jorethang': ['Jorethang City', 'Namchi', 'Nayabazar', 'Rishi', 'Sumbuk'],
    'Nayabazar': ['Nayabazar City', 'Jorethang', 'Namchi', 'Rishi'],
    'Yuksom': ['Yuksom City', 'Tashiding', 'Pelling', 'Gerethang'],
    'Ravangla': ['Ravangla City', 'Namchi', 'Yangang', 'Damthang', 'Temi'],
    'Lachen': ['Lachen City', 'Chungthang', 'Thangu', 'Gurudongmar'],
    'Lachung': ['Lachung City', 'Chungthang', 'Yumthang', 'Mangan'],
    'Pelling': ['Pelling City', 'Gyalshing', 'Yuksom', 'Dentam', 'Darap'],
    'Legship': ['Legship City', 'Gyalshing', 'Ravangla', 'Tashiding'],
    'Chungthang': ['Chungthang City', 'Lachen', 'Lachung', 'Mangan'],

    // ── Tamil Nadu Districts ──
    'Chennai': ['Chennai City', 'Tambaram', 'Chromepet', 'Pallavaram', 'Avadi', 'Ambattur', 'Perambur', 'Velachery'],
    'Coimbatore': ['Coimbatore City', 'Pollachi', 'Mettupalayam', 'Sulur', 'Annur', 'Kinathukadavu'],
    'Madurai': ['Madurai City', 'Melur', 'Thirumangalam', 'Usilampatti', 'Peraiyur', 'Vadipatti'],
    'Tiruchirappalli': ['Tiruchirappalli City', 'Srirangam', 'Lalgudi', 'Musiri', 'Thuraiyur', 'Manapparai'],
    'Salem': ['Salem City', 'Attur', 'Mettur', 'Edappadi', 'Omalur', 'Sankagiri'],
    'Tirunelveli': ['Tirunelveli City', 'Palayamkottai', 'Ambasamudram', 'Tenkasi', 'Sankarankovil', 'Cheranmahadevi'],
    'Tiruppur': ['Tiruppur City', 'Avinashi', 'Palladam', 'Udumalpet', 'Kangeyam', 'Dharapuram'],
    'Vellore': ['Vellore City', 'Ranipet', 'Arcot', 'Ambur', 'Gudiyatham', 'Vaniyambadi'],
    'Erode': ['Erode City', 'Bhavani', 'Gobichettipalayam', 'Sathyamangalam', 'Perundurai', 'Anthiyur'],
    'Thoothukkudi': ['Thoothukkudi City', 'Kovilpatti', 'Tiruchendur', 'Kayalpattinam', 'Eral', 'Srivaikuntam'],
    'Dindigul': ['Dindigul City', 'Palani', 'Kodaikanal', 'Nilakottai', 'Oddanchatram', 'Natham'],
    'Thanjavur': ['Thanjavur City', 'Kumbakonam', 'Pattukkottai', 'Papanasam', 'Orathanadu', 'Thiruvidaimarudur'],
    'Ranipet': ['Ranipet City', 'Arcot', 'Sholinghur', 'Walajapet', 'Arakkonam'],
    'Sivakasi': ['Sivakasi City', 'Virudhunagar', 'Rajapalayam', 'Srivilliputhur', 'Aruppukkottai'],
    'Karur': ['Karur City', 'Kulithalai', 'Aravakurichi', 'Krishnarayapuram', 'Kadavur'],
    'Nagercoil': ['Nagercoil City', 'Marthandam', 'Colachel', 'Thuckalay', 'Kuzhithurai', 'Padmanabhapuram'],
    'Hosur': ['Hosur City', 'Krishnagiri', 'Denkanikottai', 'Shoolagiri', 'Kelamangalam'],
    'Kanchipuram': ['Kanchipuram City', 'Sriperumbudur', 'Chengalpattu', 'Mamallapuram', 'Uthiramerur'],
    'Kumarapalayam': ['Kumarapalayam City', 'Namakkal', 'Rasipuram', 'Tiruchengode', 'Paramathi'],
    'Kanyakumari': ['Kanyakumari City', 'Nagercoil', 'Marthandam', 'Colachel', 'Thuckalay'],
    'Namakkal': ['Namakkal City', 'Rasipuram', 'Tiruchengode', 'Kumarapalayam', 'Paramathi', 'Mohanur'],
    'Tiruvannamalai': ['Tiruvannamalai City', 'Arani', 'Polur', 'Cheyyar', 'Vandavasi', 'Kilpennathur'],
    'Pollachi': ['Pollachi City', 'Valparai', 'Kinathukadavu', 'Udumalpet', 'Anamalai'],
    'Kumbakonam': ['Kumbakonam City', 'Mayiladuthurai', 'Sirkazhi', 'Papanasam', 'Thiruvidaimarudur'],
    'Rajapalayam': ['Rajapalayam City', 'Srivilliputhur', 'Virudhunagar', 'Watrap', 'Sankarankovil'],

    // ── Telangana Districts ──
    'Hyderabad': ['Hyderabad City', 'Secunderabad', 'Kukatpally', 'Madhapur', 'Gachibowli', 'Begumpet', 'Ameerpet'],
    'Warangal': ['Warangal City', 'Hanamkonda', 'Kazipet', 'Jangaon', 'Mahabubabad', 'Narsampet'],
    'Nizamabad': ['Nizamabad City', 'Bodhan', 'Armoor', 'Kamareddy', 'Banswada', 'Yellareddy'],
    'Karimnagar': ['Karimnagar City', 'Jagtial', 'Peddapalli', 'Ramagundam', 'Godavarikhani', 'Huzurabad'],
    'Khammam': ['Khammam City', 'Kothagudem', 'Bhadrachalam', 'Sathupalli', 'Wyra', 'Madhira'],
    'Ramagundam': ['Ramagundam City', 'Godavarikhani', 'Mancherial', 'Bellampalli', 'Peddapalli'],
    'Mahbubnagar': ['Mahbubnagar City', 'Jadcherla', 'Shadnagar', 'Achampet', 'Kalwakurthy', 'Nagarkurnool'],
    'Nalgonda': ['Nalgonda City', 'Miryalaguda', 'Suryapet', 'Devarakonda', 'Bhongir', 'Nakrekal'],
    'Adilabad': ['Adilabad City', 'Nirmal', 'Mancherial', 'Luxettipet', 'Bhainsa', 'Mudhole'],
    'Suryapet': ['Suryapet City', 'Kodad', 'Huzurnagar', 'Neredcherla', 'Mellacheruvu'],
    'Siddipet': ['Siddipet City', 'Gajwel', 'Husnabad', 'Dubbak', 'Medak', 'Toguta'],
    'Miryalaguda': ['Miryalaguda City', 'Nalgonda', 'Halia', 'Dameracherla', 'Tripuraram'],
    'Jagtial': ['Jagtial City', 'Koratla', 'Metpally', 'Raikal', 'Dharmapuri'],
    'Mancherial': ['Mancherial City', 'Bellampalli', 'Naspur', 'Jaipur', 'Kyathampally'],
    'Kothagudem': ['Kothagudem City', 'Bhadrachalam', 'Palwancha', 'Manuguru', 'Yellandu'],
    'Zahirabad': ['Zahirabad City', 'Sangareddy', 'Narayankhed', 'Andole', 'Nyalkal'],
    'Bodhan': ['Bodhan City', 'Nizamabad', 'Armoor', 'Ranjal', 'Varni'],
    'Sangareddy': ['Sangareddy City', 'Zahirabad', 'Narayankhed', 'Patancheru', 'Sadasivpet'],
    'Kamareddy': ['Kamareddy City', 'Banswada', 'Yellareddy', 'Nizamabad', 'Domakonda'],
    'Nirmal': ['Nirmal City', 'Bhainsa', 'Khanapur', 'Mudhole', 'Dilawarpur'],

    // ── Tripura Districts ──
    'Agartala': ['Agartala City', 'Badharghat', 'Jirania', 'Mohanpur', 'Udaipur', 'Bishalgarh'],
    'Udaipur (Tripura)': ['Udaipur City', 'Amarpur', 'Sabroom', 'Belonia', 'Radhakishorepur'],
    'Dharmanagar': ['Dharmanagar City', 'Kailasahar', 'Kumarghat', 'Panisagar', 'Kadamtala'],
    'Kailasahar': ['Kailasahar City', 'Kumarghat', 'Dharmanagar', 'Kamalpur', 'Ambassa'],
    'Belonia': ['Belonia City', 'Sabroom', 'Santirbazar', 'Rajnagar', 'Hrishyamukh'],
    'Khowai': ['Khowai City', 'Teliamura', 'Kalyanpur', 'Tulashikhar', 'Padmabil'],
    'Ambassa': ['Ambassa City', 'Kamalpur', 'Gandacherra', 'Salema', 'Raishyabari'],
    'Sabroom': ['Sabroom City', 'Belonia', 'Satchand', 'Pilak', 'Manubazar'],
    'Sonamura': ['Sonamura City', 'Melaghar', 'Bishalgarh', 'Udaipur', 'Amarpur'],
    'Kumarghat': ['Kumarghat City', 'Kailasahar', 'Dharmanagar', 'Kamalpur'],
    'Bishalgarh': ['Bishalgarh City', 'Melaghar', 'Sonamura', 'Jirania', 'Udaipur'],
    'Amarpur': ['Amarpur City', 'Udaipur', 'Sabroom', 'Karbook', 'Matabari'],
    'Melaghar': ['Melaghar City', 'Sonamura', 'Bishalgarh', 'Udaipur'],
    'Jirania': ['Jirania City', 'Agartala', 'Mohanpur', 'Bishalgarh'],
    'Teliamura': ['Teliamura City', 'Khowai', 'Kalyanpur', 'Ambassa'],

    // ── Union Territory Districts ──
    // Andaman and Nicobar Islands
    'Port Blair': ['Port Blair City', 'Aberdeen Bazaar', 'Haddo', 'Junglighat', 'Garacharma', 'Bamboo Flat'],
    'Diglipur': ['Diglipur City', 'Aerial Bay', 'Kalipur', 'Ramnagar', 'Kalighat'],
    'Rangat': ['Rangat City', 'Billiground', 'Nimbudera', 'Bakultala', 'Kadamtala'],
    'Mayabunder': ['Mayabunder City', 'Webi', 'Karmatang', 'Danapur'],
    'Car Nicobar': ['Car Nicobar City', 'Malacca', 'Sawai', 'Kimios'],
    'Bamboo Flat': ['Bamboo Flat City', 'Chatham', 'Port Blair', 'Garacharma'],

    // Chandigarh
    'Chandigarh': ['Chandigarh City', 'Manimajra', 'Sector 17', 'Sector 22', 'Sector 35', 'Industrial Area'],
    'Manimajra': ['Manimajra City', 'Chandigarh', 'Burail', 'IT Park'],

    // Delhi
    'New Delhi': ['New Delhi City', 'Connaught Place', 'Lodhi Colony', 'Chanakyapuri', 'India Gate Area'],
    'North Delhi': ['Civil Lines', 'Model Town', 'Kamla Nagar', 'Shakti Nagar', 'Timarpur'],
    'South Delhi': ['Greater Kailash', 'Saket', 'Hauz Khas', 'Lajpat Nagar', 'Defence Colony'],
    'East Delhi': ['Laxmi Nagar', 'Preet Vihar', 'Vivek Vihar', 'Anand Vihar', 'Patparganj'],
    'West Delhi': ['Janakpuri', 'Rajouri Garden', 'Tilak Nagar', 'Vikaspuri', 'Tagore Garden'],
    'Central Delhi': ['Karol Bagh', 'Rajender Nagar', 'Patel Nagar', 'Daryaganj'],
    'North East Delhi': ['Seelampur', 'Jaffrabad', 'Maujpur', 'Bhajanpura', 'Yamuna Vihar'],
    'North West Delhi': ['Rohini', 'Pitampura', 'Shalimar Bagh', 'Model Town', 'Wazirpur'],
    'South West Delhi': ['Dwarka', 'Najafgarh', 'Kapashera', 'Palam'],
    'South East Delhi': ['Okhla', 'Kalkaji', 'Badarpur', 'Tughlakabad', 'Jasola'],
    'Shahdara': ['Shahdara City', 'Seelampur', 'Seemapuri', 'New Seemapuri', 'Nand Nagri'],
    'Dwarka': ['Dwarka City', 'Palam', 'Dabri', 'Sagarpur', 'Najafgarh'],
    'Rohini': ['Rohini City', 'Pitampura', 'Shalimar Bagh', 'Badli', 'Rithala'],
    'Pitampura': ['Pitampura City', 'Rohini', 'Shalimar Bagh', 'Netaji Subhash Place'],
    'Narela': ['Narela City', 'Bawana', 'Alipur', 'Holambi Kalan'],
    'Najafgarh': ['Najafgarh City', 'Dwarka', 'Kapashera', 'Dichaon Kalan', 'Chhawla'],
    'Mehrauli': ['Mehrauli City', 'Qutub Minar Area', 'Chhatarpur', 'Vasant Kunj'],
    'Okhla': ['Okhla City', 'Jasola', 'Jamia Nagar', 'Abul Fazal Enclave'],
    'Chandni Chowk': ['Chandni Chowk City', 'Red Fort Area', 'Jama Masjid', 'Kinari Bazar'],
    'Karol Bagh': ['Karol Bagh City', 'Rajender Nagar', 'Patel Nagar', 'Ajmal Khan Road'],

    // Jammu and Kashmir
    'Srinagar': ['Srinagar City', 'Lal Chowk', 'Dal Gate', 'Hazratbal', 'Nishat', 'Rainawari'],
    'Jammu': ['Jammu City', 'Gandhi Nagar', 'Trikuta Nagar', 'Channi Himmat', 'Rehari'],
    'Anantnag': ['Anantnag City', 'Pahalgam', 'Kokernag', 'Shangus', 'Bijbehara'],
    'Baramulla': ['Baramulla City', 'Sopore', 'Pattan', 'Uri', 'Tangmarg', 'Kreeri'],
    'Sopore': ['Sopore City', 'Baramulla', 'Handwara', 'Rafiabad', 'Watlab'],
    'Udhampur': ['Udhampur City', 'Ramnagar', 'Majalta', 'Chenani', 'Panchari'],
    'Kathua': ['Kathua City', 'Billawar', 'Hiranagar', 'Bashohli', 'Lakhanpur'],
    'Kupwara': ['Kupwara City', 'Handwara', 'Tangdar', 'Trehgam', 'Drugmulla'],
    'Pulwama': ['Pulwama City', 'Awantipora', 'Tral', 'Pampore', 'Shopian'],
    'Rajouri': ['Rajouri City', 'Nowshera', 'Sunderbani', 'Thanamandi', 'Darhal'],
    'Poonch': ['Poonch City', 'Surankote', 'Mendhar', 'Mandi', 'Haveli'],
    'Kishtwar': ['Kishtwar City', 'Paddar', 'Marwah', 'Dacchan', 'Chatroo'],
    'Kulgam': ['Kulgam City', 'Qazigund', 'D.H. Pora', 'Yaripora', 'Devsar'],
    'Bandipore': ['Bandipore City', 'Sumbal', 'Gurez', 'Hajin', 'Aloosa'],
    'Ganderbal': ['Ganderbal City', 'Kangan', 'Lar', 'Wakura', 'Sonamarg'],
    'Reasi': ['Reasi City', 'Katra', 'Arnas', 'Mahore', 'Pouni'],
    'Samba': ['Samba City', 'Vijaypur', 'Ramgarh', 'Ghagwal', 'Bari Brahmana'],
    'Shopian': ['Shopian City', 'Pulwama', 'Zainapora', 'Kellar', 'Imamsahib'],
    'Budgam': ['Budgam City', 'Magam', 'Chadoora', 'Khansahib', 'Beerwah'],
    'Doda': ['Doda City', 'Bhaderwah', 'Thathri', 'Gandoh', 'Kahara'],

    // Ladakh
    'Leh': ['Leh City', 'Hemis', 'Thikse', 'Stok', 'Choglamsar', 'Spituk'],
    'Kargil': ['Kargil City', 'Drass', 'Sankoo', 'Zanskar', 'Shakar Chictan'],
    'Diskit': ['Diskit City', 'Hunder', 'Panamik', 'Turtuk', 'Sumur'],
    'Nyoma': ['Nyoma City', 'Hanle', 'Loma', 'Chumur', 'Mahe'],
    'Hanle': ['Hanle City', 'Nyoma', 'Loma', 'Chumur'],
    'Tangtse': ['Tangtse City', 'Durbuk', 'Pangong', 'Lukung', 'Man'],
    'Turtuk': ['Turtuk City', 'Tyakshi', 'Diskit', 'Hunder'],
    'Zanskar': ['Padum', 'Karsha', 'Stongde', 'Zangla', 'Pishu'],
    'Drass': ['Drass City', 'Mushkoh', 'Bhimbat', 'Minamarg'],
    'Sankoo': ['Sankoo City', 'Kargil', 'Panikhar', 'Suru'],

    // Puducherry
    'Puducherry': ['Puducherry City', 'White Town', 'Auroville', 'Lawspet', 'Mudaliarpet', 'Reddiarpalayam'],
    'Karaikal': ['Karaikal City', 'Thirunallar', 'Nedungadu', 'Kottucherry', 'Varichikudi'],
    'Mahe': ['Mahe City', 'Palloor', 'Pandakal', 'Chalakara'],
    'Yanam': ['Yanam City', 'Farampeta', 'Agraharam', 'Kanakalapeta'],
    'Ozhukarai': ['Ozhukarai City', 'Puducherry', 'Ariyankuppam', 'Nettapakkam'],
    'Villianur': ['Villianur City', 'Puducherry', 'Bahour', 'Mannadipet'],
    'Bahour': ['Bahour City', 'Puducherry', 'Villianur', 'Embalam'],
    'Ariyankuppam': ['Ariyankuppam City', 'Puducherry', 'Thavalakuppam', 'Katterikuppam'],
    'Nettapakkam': ['Nettapakkam City', 'Ozhukarai', 'Puducherry', 'Villianur'],
    'Mannadipet': ['Mannadipet City', 'Villianur', 'Puducherry', 'Bahour'],

    // Lakshadweep
    'Kavaratti': ['Kavaratti Island', 'Main Bazaar', 'Beach Area'],
    'Agatti': ['Agatti Island', 'Agatti Airport Area', 'Beach Side'],
    'Amini': ['Amini Island', 'North Village', 'South Village'],
    'Andrott': ['Andrott Island', 'East Village', 'West Village'],
    'Kadmat': ['Kadmat Island', 'Beach Resort Area', 'Village Center'],
    'Kalpeni': ['Kalpeni Island', 'Kalpeni Village', 'Tilakkam'],
    'Kiltan': ['Kiltan Island', 'Kiltan Village'],
    'Chetlat': ['Chetlat Island', 'Chetlat Village'],
    'Bitra': ['Bitra Island', 'Bitra Village'],
    'Minicoy': ['Minicoy Island', 'Minicoy Village', 'Tuna Canning Area'],

    // Dadra and Nagar Haveli and Daman and Diu
    'Daman': ['Daman City', 'Nani Daman', 'Moti Daman', 'Devka Beach', 'Jampore'],
    'Diu': ['Diu City', 'Nagoa', 'Fudam', 'Vanakbara', 'Ghoghla'],
    'Silvassa': ['Silvassa City', 'Amli', 'Khanvel', 'Naroli', 'Dadra'],
    'Amli': ['Amli City', 'Silvassa', 'Khanvel', 'Selvas'],
    'Khanvel': ['Khanvel City', 'Silvassa', 'Dudhani', 'Amli'],
  };

  /// Get all states (merged from potato-farming data + comprehensive list)
  static List<String> get states {
    final allKeys = <String>{
      ...stateCities.keys,
      ...IndianStatesAndCities.statesAndCities.keys,
    };
    return allKeys.toList()..sort();
  }

  /// Get districts/cities for a state (merged from both data sources)
  static List<String> getCitiesForState(String state) {
    final cities = <String>{
      ...stateCities[state] ?? [],
      ...IndianStatesAndCities.statesAndCities[state] ?? [],
    };
    final result = cities.toList()..sort();
    return result;
  }

  /// Get villages/towns for a district
  static List<String> getVillagesForDistrict(String district) {
    return districtVillages[district] ?? [];
  }

  /// Check if a district has villages data
  static bool hasVillagesData(String district) {
    return districtVillages.containsKey(district);
  }
}
